/* Formatted on 8/3/2021 9:51:39 AM (QP5 v5.287) */
CREATE OR REPLACE FORCE VIEW APPS.XXDBL_GL_DTL_STAT_MV#
(
   SL,
   APPLICATION_ID,
   JE_SOURCE,
   JE_CATEGORY,
   UNIT_NAME,
   COMPANY,
   LOCATION,
   PRODUCT_LINE,
   COST_CENTER,
   ACCOUNT,
   SUB_ACCOUNT,
   INTER_COMPANY,
   EXPENSE_CATEGORY,
   FUTURE,
   ACCTDESC,
   VOUCHER_NUMBER_2,
   VOUCHER_NUMBER,
   GL_VOUCHER_NUMBER,
   GL_JE_LINE_NUM,
   VOUCHER_DATE,
   DESCRIPTION,
   CURRENCY_CODE,
   CONVERSION_RATE,
   CREATED_BY,
   ENTERED_DEBITS,
   ENTERED_CREDITS,
   DEBITS,
   CREDITS,
   REVERSAL_TYPE,
   REVERSE_PERIOD,
   CHEQUE_NUMBER,
   CHEQUE_DATE,
   PARTY_CODE,
   PARTY_NAME,
   TRANSACTION_TYPE,
   CHART_OF_ACCOUNTS_ID,
   LEDGER_ID,
   DFF_CONTEXT,
   ATTRIBUTE1,
   ATTRIBUTE2,
   ATTRIBUTE3,
   ATTRIBUTE4,
   ATTRIBUTE5
)
   BEQUEATH DEFINER
AS
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJH.JE_HEADER_ID = 489614
   UNION ALL
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND NVL (GJH.JE_FROM_SLA_FLAG, 'N') <> 'Y'
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
   UNION ALL
   --OPM Batch Close
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
          AND CAT.NAME = 'OPM Batch Close'
   UNION ALL
   -- Receivable Transaction Invoice
   SELECT 2 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.BILL_TO_CUSTOMER_ID
          AND CT.CUSTOMER_TRX_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          AND XTE.ENTITY_CODE IN ('TRANSACTIONS')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Bill Receivable
   SELECT 3 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          CT.TRX_NUMBER VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.DRAWEE_ID
          AND CT.CUSTOMER_TRX_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          AND XTE.ENTITY_CODE IN ('BILLS_RECEIVABLE')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Only for Adjustoments
   SELECT 4 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (ADJ.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          AR_ADJUSTMENTS_ALL ADJ,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.BILL_TO_CUSTOMER_ID
          AND CT.CUSTOMER_TRX_ID = ADJ.CUSTOMER_TRX_ID
          AND ADJ.ADJUSTMENT_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          AND XTE.ENTITY_CODE IN ('ADJUSTMENTS')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Receipt
   SELECT 5 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CR.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Rcv No-' || CR.RECEIPT_NUMBER)
             PARTICULARS,
          CR.CURRENCY_CODE,
          CR.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CR.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CR.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CR.ATTRIBUTE1,
          CR.ATTRIBUTE2,
          CR.ATTRIBUTE3,
          CR.ATTRIBUTE4,
          CR.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          AR_CASH_RECEIPTS_ALL CR,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID(+) = CR.PAY_FROM_CUSTOMER
          AND CUST.ORG_ID(+) = CR.ORG_ID
          AND CR.CASH_RECEIPT_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.ENTITY_CODE = 'RECEIPTS'
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND NVL (NVL (XAL.ACCOUNTED_DR, XAL.ACCOUNTED_CR), 0) <> 0
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE(+) = 'BILL_TO'
          AND CUST.PRIMARY_FLAG(+) = 'Y'
   UNION ALL
   -- Payables Invoice
   SELECT 6 SL,
          200 APPLICATION_ID,
          'AP' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (API.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          XAL.DESCRIPTION PARTICULARS,
          API.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          API.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (API.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          API.INVOICE_NUM CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          API.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          API.ATTRIBUTE1,
          API.ATTRIBUTE2,
          API.ATTRIBUTE3,
          API.ATTRIBUTE4,
          API.ATTRIBUTE5
     FROM AP_SUPPLIERS APS,
          AP_INVOICES_ALL API,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     NVL (APS.VENDOR_ID(+), -222) = API.VENDOR_ID
          AND API.INVOICE_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.ENTITY_CODE = 'AP_INVOICES'
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 200
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   -- Payables Invoice Payment
   SELECT 7 SL,
          200 APPLICATION_ID,
          'AP' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (APC.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          APC.DESCRIPTION PARTICULARS,
          APC.CURRENCY_CODE,
          APC.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (APC.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          TO_CHAR (APC.CHECK_NUMBER) CHEQUE_NUMBER,
          TRUNC (APC.CHECK_DATE) CHEQUE_DATE,
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          APC.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          APC.ATTRIBUTE1,
          APC.ATTRIBUTE2,
          APC.ATTRIBUTE3,
          APC.ATTRIBUTE4,
          APC.ATTRIBUTE5
     FROM AP_CHECKS_ALL APC,
          AP_SUPPLIERS APS,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     APC.VENDOR_ID = NVL (APS.VENDOR_ID(+), -222)
          AND APC.CHECK_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_CODE = 'AP_PAYMENTS'
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 200
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   -- Bank Transfer
   SELECT 8 SL,
          260 APPLICATION_ID,
          'CM' JE_SOURCE,
          GJH.JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          CPT.TRXN_REFERENCE_NUMBER VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GLL.JE_LINE_NUM GL_JE_LINE_NUM,
          XEL.ACCOUNTING_DATE VOUCHER_DATE,
          NULL PARTICULARS,
          CFLOW.CASHFLOW_CURRENCY_CODE CURRENCY_CODE,
          CFLOW.CASHFLOW_EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CFLOW.CREATED_BY)
             CREATED_BY,
          NVL (XEL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XEL.ENTERED_CR, 0) ENTERED_CREDITS,
          XEL.ACCOUNTED_DR,
          XEL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          CPT.ATTRIBUTE1 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CPT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CPT.ATTRIBUTE1,
          CPT.ATTRIBUTE2,
          CPT.ATTRIBUTE3,
          CPT.ATTRIBUTE4,
          CPT.ATTRIBUTE5
     FROM GL_JE_LINES GLL,
          GL_JE_HEADERS GJH,
          GL_IMPORT_REFERENCES GIR,
          XLA_AE_LINES XEL,
          XLA_AE_HEADERS XEH,
          CE_PAYMENT_TRANSACTIONS CPT,
          CE_CASHFLOWS CFLOW,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     XTE.APPLICATION_ID = 260
          AND XEL.APPLICATION_ID = XEH.APPLICATION_ID
          AND XTE.APPLICATION_ID = XEH.APPLICATION_ID
          AND XEL.AE_HEADER_ID = XEH.AE_HEADER_ID
          AND XTE.ENTITY_CODE = 'CE_CASHFLOWS'
          AND XTE.SOURCE_ID_INT_1 = CFLOW.CASHFLOW_ID
          AND CPT.TRXN_REFERENCE_NUMBER = CFLOW.TRXN_REFERENCE_NUMBER
          AND XTE.ENTITY_ID = XEH.ENTITY_ID
          AND XEL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GIR.JE_HEADER_ID = GLL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GLL.JE_LINE_NUM
          AND (   NVL (XEL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XEL.ACCOUNTED_CR, 0) <> 0)
          AND GLL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GLL.STATUS = 'P'
   UNION ALL
   SELECT 9 SL,
          140 APPLICATION_ID,
          'FA' JE_SOURCE,
          GJH.JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJL.EFFECTIVE_DATE VOUCHER_DATE,
          XAL.DESCRIPTION PARTICULARS,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL,
          NULL,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          NULL,
          NULL,
          NULL,
          NULL,
          NULL,
          NULL
     FROM XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 140
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   SELECT 10 SL,
          XAL.APPLICATION_ID,
          'DIS_INV' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_ORGANIZATION_NAME (MMT.ORGANIZATION_ID)
             UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          NVL (
             TO_NUMBER (APPS.XX_GET_RCV_NUMBER_FROM_TRX_ID (SOURCE_ID_INT_1)),
             GJH.DOC_SEQUENCE_VALUE)
             VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          MSI.DESCRIPTION PARTICULARS,
          MMT.CURRENCY_CODE,
          MMT.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          APPS.XX_GET_LC_NUMBER_FROM_TRX_ID (SOURCE_ID_INT_1) CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APPS.XX_GET_VENDOR_CODE_FROM_TRX_ID (SOURCE_ID_INT_1) PARTY_CODE,
          APPS.XX_GET_VENDOR_NAME_FROM_TRX_ID (SOURCE_ID_INT_1) PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          MMT.ATTRIBUTE_CATEGORY,
          MMT.ATTRIBUTE1,
          MMT.ATTRIBUTE2,
          MMT.ATTRIBUTE3,
          MMT.ATTRIBUTE4,
          MMT.ATTRIBUTE5
     FROM XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX,
          MTL_MATERIAL_TRANSACTIONS MMT,
          APPS.MTL_SYSTEM_ITEMS_B MSI
    WHERE     XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID NOT IN (140,
                                         200,
                                         222,
                                         260,
                                         555)
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND XTE.SOURCE_ID_INT_1 = MMT.TRANSACTION_ID(+)
          AND MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
          AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID
   UNION ALL
   SELECT 12 SL,                                            ----ADDED BY Majid
          XAH.APPLICATION_ID,
          'OPM_INV' JE_SOURCE,
          XAH.JE_CATEGORY_NAME JE_CATEGORY,
          ORG.ORGANIZATION_NAME UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GXEH.TRANSACTION_ID VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          XAL.AE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          NULL PARTICULARS,
          GXEH.CURRENCY_CODE,
          GXEH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GXEH.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          XAH.LEDGER_ID,
          NULL DFF_CONTEXT,
          NULL ATTRIBUTE1,
          NULL ATTRIBUTE2,
          NULL ATTRIBUTE3,
          NULL ATTRIBUTE4,
          NULL ATTRIBUTE5
     FROM GMF_XLA_EXTRACT_HEADERS GXEH,
          XLA_AE_LINES XAL,
          XLA_AE_HEADERS XAH,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX,
          MTL_SYSTEM_ITEMS_B_KFV MST,
          ORG_ORGANIZATION_DEFINITIONS ORG,
          MTL_ITEM_CATEGORIES_V MIC,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL
    WHERE     XAH.EVENT_ID = GXEH.EVENT_ID
          AND XAH.LEDGER_ID = GXEH.LEDGER_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND MIC.CATEGORY_SET_ID = 1
          AND XAL.APPLICATION_ID = 555
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GXEH.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND GXEH.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND GXEH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
          AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          --SubLedger to GL Joining Start
          AND XAH.LEDGER_ID = GJH.LEDGER_ID                  -- ADDED BY MAJID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P';

--------------------------------------------------------------------------------
EXEC ad_zd_mview.upgrade('APPS','XXDBL_GL_DTL_STAT_MV');

SELECT *
  FROM dba_objects
 WHERE object_name LIKE 'XXDBL_GL_DTL_STAT_MV%';


--------------------------------------------------------------------------------


EXECUTE dbms_mview.refresh('APPS.XXDBL_GL_DTL_STAT_MV',method =>'C',ATOMIC_REFRESH=>FALSE);

EXECUTE DBMS_MVIEW.REFRESH_ALL_MVIEWS(failures,'C','', TRUE, FALSE, FALSE);

BEGIN
   DBMS_MVIEW.refresh ('APPS.XXDBL_GL_DTL_STAT_MV',
                       method           => 'C',
                       atomic_refresh   => FALSE);
END;

EXECUTE dbms_mview.refresh('APPS.XXDBL_GL_DTL_STAT_MV','C', NULL, TRUE,FALSE,1,0,0,FALSE,FALSE,TRUE);


--------------------------------------------------------------------------------


BEGIN
   SYS.DBMS_SCHEDULER.create_job (
      job_name          => 'XXDBL_MVIEW_SCHEDULER',
      job_type          => 'PLSQL_BLOCK',
      job_action        => 'BEGIN EXECUTE dbms_mview.refresh(''APPS.XXDBL_GL_DTL_STAT_MV'',method => ''C'',ATOMIC_REFRESH=>FALSE) END;',
      start_date        => SYSTIMESTAMP,
      repeat_interval   => 'freq=hourly; byminute=0',
      end_date          => NULL,
      enabled           => TRUE,
      comments          => 'Job defined entirely by the CREATE JOB procedure.');
END;
/


BEGIN
   SYS.DBMS_SCHEDULER.DROP_JOB (job_name => 'APPS.XXDBL_MVIEW_SCHEDULER');
END;
/


BEGIN
   SYS.DBMS_SCHEDULER.create_job (
      job_name          => 'XXDBL_MVIEW_SCHEDULER',
      job_type          => 'STORED_PROCEDURE',
      job_action        => 'APPS.XXDBL_MVIEW_DTLD_PKG.RUN_MVIEW_DATALOAD_PROC',
      start_date        => SYSTIMESTAMP,
      repeat_interval   => 'freq=minutely; interval=15; bysecond=0;',
      end_date          => NULL,
      enabled           => TRUE,
      comments          => 'Job defined entirely by the CREATE JOB procedure.');
END;
/

BEGIN
   SYS.DBMS_SCHEDULER.create_job (
      job_name          => 'XXDBL_MVIEW_SCHEDULER',
      job_type          => 'PLSQL_BLOCK',
      job_action        => 'BEGIN APPS.XXDBL_MVIEW_DTLD_PKG.RUN_MVIEW_DATALOAD_PROC; END;',
      start_date        => SYSTIMESTAMP,
      repeat_interval   => 'freq=daily; byhour=1; byminute=0; bysecond=0;',
      end_date          => NULL,
      enabled           => TRUE,
      comments          => 'Job Scheduled Created for Update Materialized View.');
END;
/

BEGIN
   DBMS_SCHEDULER.set_attribute (
      name        => 'APPS.XXDBL_MVIEW_SCHEDULER',
      attribute   => 'repeat_interval',
      VALUE       => 'freq=daily; byhour=1,13; byminute=30; bysecond=0;');
END;
/


 EXECUTE SYS.DBMS_SYNC_REFRESH.REGISTER_MVIEWS('XXDBL_GL_DTL_STAT_MV');



-- Display job run details.

  SELECT *
    FROM all_scheduler_job_run_details
   WHERE 1 = 1 AND job_name = 'XXDBL_MVIEW_SCHEDULER'
ORDER BY actual_start_date DESC;

--------------------------------------------------------------------------------


SELECT *
  FROM APPS.XXDBL_GL_DTL_STAT_MV
 WHERE 1 = 1
--AND PERIOD_DESC = 'FEB-21'
--AND ORGANIZATION_ID = 195
;
 --------------------------------------------------------------------------
      ----------XXDBL_GL_DTL_STAT_MV MVIEW DATALOAD--------------------------
      --------------------------------------------------------------------------

BEGIN
   IF p_mview = 'XXDBL_GL_DTL_STAT_MV'
   THEN
      BEGIN
         x_mview_name := 'XXDBL_GL_DTL_STAT_MV';
         DBMS_MVIEW.REFRESH ('APPS.XXDBL_GL_DTL_STAT_MV',
                             METHOD           => 'C',
                             ATOMIC_REFRESH   => FALSE);
         COMMIT;
         fnd_file.put_line (
            fnd_file.LOG,
            'Successfully Refresh the Materialized View :' || x_mview_name);
      END;
   END IF;
END;