--Product Family-wise Wholesale Sales Summary (Wholesale/Corporate)
select P.PRODUCT_FAMILY,
       SUM(W.SALES_QUANTITY) SALES_QUANTITY,
       SUM(W.SALES_PRICE) SALES_PRICE
  from IFSAPP.SBL_VW_WHOLESALE_SALES_NEW w
 INNER JOIN IFSAPP.SBL_JR_PRODUCT_DTL_INFO P
    ON W.PRODUCT_CODE = P.PRODUCT_CODE
 WHERE W.SITE != 'SCSM'
   AND W.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
 GROUP BY P.PRODUCT_FAMILY
 ORDER BY P.PRODUCT_FAMILY
