SELECT
    H.YEAR,
    H.PERIOD,
    COUNT(H.ACCT_NO) TOTAL_ACCOUNTS,
    SUM(H.ARR_AMT) TOTAL_ARR_AMT,
    SUM(H.ACT_OUT_BAL) TOTAL_ACT_OUT_BAL
FROM HPNRET_FORM249_ARREARS_TAB H
WHERE H.ACT_OUT_BAL > 0 AND
  H.YEAR = '&year_i' AND
  H.PERIOD = '&month_i' AND
  H.GROUP_SALE_NO IS NOT NULL
GROUP BY H.YEAR, H.PERIOD
