SELECT T.price_list_no,
       T.SALE_PART_NO,
       T.PART_DESC,
       T.BRAND,
       T.PRODUCT_FAMILY,
       T.COMMODITY_GROUP2,
       T.VALID_FROM_DATE,
       T.SALE_PRICE_NSP,
       T.TAX_CODE,
       T.TAX_RATE,
       T.CO_DISCOUNT,
       DECODE(T.SALE_PRICE_NSP, 0, 0, ROUND((T.CO_DISCOUNT/T.SALE_PRICE_NSP) * 100, 2)) "CO_DISCOUNT_",
       T.HP_DISCOUNT,
       DECODE(T.SALE_PRICE_NSP, 0, 0, ROUND((T.HP_DISCOUNT/T.SALE_PRICE_NSP) * 100, 2)) "HP_DISCOUNT_",
       T.CASH_PRICE,
       T.HIRE_CASH_PRICE,
       T.CASH_COMMISSION,
       T.HP_COMMISSION
  from IFSAPP.SBL_LATEST_PRICE_LIST T
 where T.PRICE_LIST_NO = '&PRICE_LIST_NO'
     and T.SALE_PART_NO LIKE UPPER('%&CATALOG_NO%')