SELECT
*
FROM
ALL_OBJECTS
WHERE 1=1
--AND OBJECT_TYPE IN ('TABLE','VIEW','SYNONYM')
--AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY')
--AND OBJECT_TYPE IN ('TRIGGER')
--AND OBJECT_TYPE IN ('FUNCTION')
--AND OBJECT_TYPE IN ('SEQUENCE')
--AND OBJECT_TYPE IN ('MATERIALIZED VIEW')
AND     (:P_OBJECT_TYPE IS NULL OR (UPPER(OBJECT_TYPE) LIKE UPPER('%'||:P_OBJECT_TYPE||'%') ))
AND     (:P_OBJECT_NAME IS NULL OR (UPPER(OBJECT_NAME) LIKE UPPER('%'||:P_OBJECT_NAME||'%') ))
AND     (:P_OWNER_NAME IS NULL OR (UPPER(OWNER) = UPPER(:P_OWNER_NAME) ))
--AND OBJECT_NAME LIKE '%IFSAPP%'
--AND OWNER IN ('IFSAPP','APPS')
--AND     STATUS = 'VALID'
;

------------------------------------------------------------------------------------------------

SELECT
*
FROM
ALL_TABLES
WHERE 1=1
AND     (:P_TABLE_NAME IS NULL OR (UPPER(TABLE_NAME) LIKE UPPER('%'||:P_TABLE_NAME||'%') ))
AND     (:P_OWNER_NAME IS NULL OR (UPPER(OWNER) = UPPER(:P_OWNER_NAME) ))
--AND TABLE_NAME LIKE '%IFSAPP%'
--AND OWNER IN ('IFSAPP','APPS')
;

------------------------------------------------------------------------------------------------

SELECT
*
FROM
ALL_OBJECTS
WHERE 1=1
AND OBJECT_NAME LIKE '%FA_OBJECT_TAB%'
--AND ROWNUM<=7
;