CREATE SEQUENCE XXDBL.XXDBL_BILL_CHALAN_NO_S
  START WITH 13232
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


CREATE OR REPLACE SYNONYM APPS.XXDBL_BILL_CHALAN_NO_S FOR XXDBL.XXDBL_BILL_CHALAN_NO_S;


GRANT ALTER, SELECT ON XXDBL.XXDBL_BILL_CHALAN_NO_S TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXDBL.XXDBL_BILL_CHALAN_NO_S TO APPSRO;