
SELECT 
    LH.ORIG_ORG_ID
    ,LH.NAME PRICE_LIST_NAME
    ,LH.DESCRIPTION PRICE_LIST_DESC
    ,LH.ACTIVE_FLAG ACTIVE_STATUS
    ,LH.CONTEXT PRICING_CONTEXT
    ,LH.ATTRIBUTE2 LINE_OF_BUSINESS
    ,LL.OPERAND PRICE_VALUE
    ,LL.ATTRIBUTE3 CUSTOMER_BUYER
    ,LL.CONTEXT LINE_CONTEXT
    --,LH.*
    --,LL.*
    --,PA.*
  FROM QP_LIST_HEADERS LH, QP_LIST_LINES LL, QP_PRICING_ATTRIBUTES PA
 WHERE     1 = 1
       AND LH.LIST_HEADER_ID = LL.LIST_HEADER_ID
       AND LH.LIST_HEADER_ID = PA.LIST_HEADER_ID
       AND LL.LIST_LINE_ID = PA.LIST_LINE_ID
       AND ((:P_ORG_ID IS NULL AND LH.ORIG_ORG_ID IN (125)) OR (LH.ORIG_ORG_ID=:P_ORG_ID))
       --AND LH.NAME = 'ETY-FIBER-PL'
       AND LL.END_DATE_ACTIVE>=SYSDATE;

--------------------------------------------------------------------------------

SELECT * FROM QP_LIST_LINES;

SELECT * FROM QP_LIST_HEADERS;

SELECT * FROM QP_PRICING_ATTRIBUTES;