SELECT 
FFV.APPLICATION_TABLE_NAME,        
FFV.DESCRIPTIVE_FLEXFIELD_NAME,        
FFV.CONTEXT_COLUMN_NAME,        
FFV.TITLE,        
ATT.APPLICATION_COLUMN_NAME,        
ATT.END_USER_COLUMN_NAME,        
ATT.COLUMN_SEQ_NUM,        
ATT.ENABLED_FLAG,        
ATT.REQUIRED_FLAG,        
ATT.SECURITY_ENABLED_FLAG,        
ATT.DISPLAY_FLAG,        
ATT.FLEX_VALUE_SET_ID,        
ATT.FORM_LEFT_PROMPT        
--,FFV.*   
FROM APPS.FND_DESCRIPTIVE_FLEXS_VL FFV, APPS.FND_DESCR_FLEX_COL_USAGE_VL ATT  
WHERE     FFV.DESCRIPTIVE_FLEXFIELD_NAME = ATT.DESCRIPTIVE_FLEXFIELD_NAME        
--AND FFV.DESCRIPTIVE_FLEXFIELD_NAME = 'JTF_RS_RESOURCE_EXTNS'        
--AND FFV.TITLE LIKE '%$SRS$.XXAKGONTDOBYDT%'
AND ATT.END_USER_COLUMN_NAME LIKE '%RMC%'
