SELECT
VAL_SET.FLEX_VALUE_SET_NAME
,FFV.FLEX_VALUE
,FFV.FLEX_VALUE_MEANING
,FFV.DESCRIPTION
--,FFV.*
--,VAL_SET.*
FROM
APPS.FND_FLEX_VALUE_SETS VAL_SET
,APPS.FND_FLEX_VALUES_VL FFV
WHERE 1=1
AND VAL_SET.FLEX_VALUE_SET_ID=FFV.FLEX_VALUE_SET_ID
AND VAL_SET.FLEX_VALUE_SET_NAME='AKG_Company'
--AND FLEX_VALUE='2110'