/* Formatted on 7/28/2019 5:58:48 PM (QP5 v5.287) */
SELECT FAT.APPLICATION_NAME,
       FLV.LOOKUP_TYPE,
       FLV.LOOKUP_CODE,
       FLV.MEANING,
       FLV.DESCRIPTION,
       FLV.TAG,
       FLV.ENABLED_FLAG,
       FLV.START_DATE_ACTIVE,
       FLV.END_DATE_ACTIVE
       --,FLV.*
  FROM APPS.FND_LOOKUP_VALUES FLV,
       APPS.FND_LOOKUP_TYPES FLT,
       APPS.FND_APPLICATION_TL FAT
 WHERE     1 = 1
       AND FLT.APPLICATION_ID = FAT.APPLICATION_ID
       AND FLT.LOOKUP_TYPE = FLV.LOOKUP_TYPE
       AND FLT.SECURITY_GROUP_ID = FLV.SECURITY_GROUP_ID
       AND FLT.VIEW_APPLICATION_ID = FLV.VIEW_APPLICATION_ID
       AND FLV.LANGUAGE = USERENV ('LANG')
       --AND UPPER(FLV.LOOKUP_TYPE) IN (UPPER('PRESS'))
       --AND UPPER(FLV.LOOKUP_CODE) IN (UPPER('1-D'))
       AND (:P_LOOKUP_TYPE IS NULL OR (UPPER (FLV.LOOKUP_TYPE) LIKE UPPER ('%' || :P_LOOKUP_TYPE || '%')))
       AND (:P_LOOKUP_CODE IS NULL OR (UPPER (LOOKUP_CODE) LIKE UPPER ('%' || :P_LOOKUP_CODE || '%')))
       AND (:P_MEANING IS NULL OR (UPPER (MEANING) LIKE UPPER ('%' || :P_MEANING || '%')))
       AND (:P_DESCRIPTION IS NULL OR (UPPER (FLV.DESCRIPTION) LIKE UPPER ('%' || :P_DESCRIPTION || '%')))
;

--------------------------------------------------------------------------------

/* Formatted on 12/18/2019 3:31:07 PM (QP5 v5.287) */
SELECT LOOKUP_TYPE,
       LOOKUP_CODE,
       MEANING,
       DESCRIPTION,
       START_DATE_ACTIVE,
       END_DATE_ACTIVE
       --,FLV.*
  FROM FND_LOOKUP_VALUES_VL FLV
 WHERE     1 = 1
       AND (:P_LOOKUP_TYPE IS NULL OR (UPPER (LOOKUP_TYPE) LIKE UPPER ('%' || :P_LOOKUP_TYPE || '%')))
       AND (:P_LOOKUP_CODE IS NULL OR (UPPER (LOOKUP_CODE) LIKE UPPER ('%' || :P_LOOKUP_CODE || '%')))
       AND (:P_MEANING IS NULL OR (UPPER (MEANING) LIKE UPPER ('%' || :P_MEANING || '%')))
       AND (:P_DESCRIPTION IS NULL OR (UPPER (DESCRIPTION) LIKE UPPER ('%' || :P_DESCRIPTION || '%')))
       AND ENABLED_FLAG = 'Y';
