/* Formatted on 1/20/2020 5:44:31 PM (QP5 v5.287) */
SELECT --DISTINCT
      FU.USER_ID,
      PAPF.PERSON_ID,
      NVL(PAPF.EMPLOYEE_NUMBER,PAPF.NPW_NUMBER) EMPLOYEE_NUMBER,
       (PAPF.FIRST_NAME || ' ' || PAPF.MIDDLE_NAMES || ' ' || PAPF.LAST_NAME)
          AS EMPLOYEE_NAME,
       SUBSTR (PJ.NAME, INSTR (PJ.NAME, '.') + 1) DESIGNATION,
       PAPF.START_DATE AS DATE_OF_JOINING,
       HAOU.NAME DEPARTMENT,
       PPB.NAME SALARY_BASIS,
       HLA.DESCRIPTION JOB_LOCATION,
       PPF.PAYROLL_NAME AS COMPANY_PAYROLL_NAME
       ,PAPF.CURRENT_EMP_OR_APL_FLAG
       ,PAAF.PRIMARY_FLAG
       ,PAPFS.PERSON_ID SUPERV_PERSON_ID
       ,NVL (PAPFS.EMPLOYEE_NUMBER, PAPFS.NPW_NUMBER) SUPERV_EMPNO
       ,(PAPFS.FIRST_NAME || ' ' || PAPFS.MIDDLE_NAMES || ' ' || PAPFS.LAST_NAME)
          AS SUPERVISOR_NAME
       --,PAAF.*
       --,PAPF.*
       --,PJ.*
       ---,POSE.*
       --,HAOU.*
       --,PPB.*
       --,PPG.*
       --,PPF.*
       --,HLA.*
  FROM APPS.PER_ALL_ASSIGNMENTS_F PAAF,
       APPS.PER_ALL_PEOPLE_F PAPF,
       APPS.PER_JOBS PJ,
       APPS.HR_ALL_ORGANIZATION_UNITS HAOU,
       APPS.PER_PAY_BASES PPB,
       APPS.PAY_PEOPLE_GROUPS PPG,
       APPS.PAY_PAYROLLS_F PPF,
       APPS.HR_LOCATIONS_ALL HLA,
       FND_USER FU,
       HR.PER_ALL_ASSIGNMENTS_F PAAFS,
       HR.PER_ALL_PEOPLE_F PAPFS
 WHERE    1=1 
       AND PAAF.BUSINESS_GROUP_ID = 81
       AND PAPF.PERSON_ID = PAAF.PERSON_ID(+)
       AND PAAF.JOB_ID=PJ.JOB_ID(+)
       AND PAAF.PAYROLL_ID=PPF.PAYROLL_ID(+)
       AND PAAF.LOCATION_ID = HLA.LOCATION_ID(+)
       AND PAAF.PEOPLE_GROUP_ID=PPG.PEOPLE_GROUP_ID(+)
       AND PAAF.ORGANIZATION_ID=HAOU.ORGANIZATION_ID(+)
       AND ((:P_EMP_ID IS NULL) OR (NVL(PAPF.EMPLOYEE_NUMBER,PAPF.NPW_NUMBER) = :P_EMP_ID))
       AND ((:P_EMPLOYEE_NAME IS NULL) OR (UPPER (PAPF.FIRST_NAME || ' ' || PAPF.MIDDLE_NAMES || ' ' || PAPF.LAST_NAME) LIKE UPPER ('%' || :P_EMPLOYEE_NAME || '%'))) 
       AND ((:P_DESIGNATION IS NULL) OR (UPPER (PJ.NAME) LIKE UPPER ('%' || :P_DESIGNATION || '%')))
       AND ((:P_DEPARTMENT IS NULL) OR (UPPER (HAOU.NAME) LIKE UPPER ('%' || :P_DEPARTMENT || '%'))) 
       --       AND papf.person_id = NVL ( :p_person_id, papf.person_id)
       --and NVL(PAPF.EMPLOYEE_NUMBER,PAPF.NPW_NUMBER) in ('')
       AND TRUNC (SYSDATE) BETWEEN TRUNC (PAAF.EFFECTIVE_START_DATE) AND TRUNC (PAAF.EFFECTIVE_END_DATE)
       AND TRUNC (SYSDATE) BETWEEN TRUNC (PAPF.EFFECTIVE_START_DATE) AND TRUNC (PAPF.EFFECTIVE_END_DATE)
       AND NVL(PAPF.EMPLOYEE_NUMBER,PAPF.NPW_NUMBER)= FU.USER_NAME(+)
       AND PAAF.SUPERVISOR_ID = PAPFS.PERSON_ID(+)
       AND PAPFS.PERSON_ID = PAAFS.PERSON_ID(+)
       AND TRUNC (SYSDATE) BETWEEN TRUNC (PAAFS.EFFECTIVE_START_DATE) AND TRUNC (PAAFS.EFFECTIVE_END_DATE)
       AND TRUNC (SYSDATE) BETWEEN TRUNC (PAPFS.EFFECTIVE_START_DATE) AND TRUNC (PAPFS.EFFECTIVE_END_DATE)
       --AND NVL(PAPF.CURRENT_EMP_OR_APL_FLAG,'Y') = 'Y'
       --AND PAPF.CURRENT_EMP_OR_APL_FLAG IS NULL
       --AND paaf.primary_flag = 'Y'
       ;