/* Formatted on 9/2/2021 10:18:07 AM (QP5 v5.354) */
SELECT i.USER_ID,
       u.USER_NAME,
       i.REFERENCE_PATH,
       i.PROMPT,
       i.RESPONSIBILITY_ID,
       i.RESPONSIBILITY_APPLICATION_ID,
       i.SECURITY_GROUP_ID
  FROM ICX_CUSTOM_MENU_ENTRIES i, FND_USER u
 WHERE i.FUNCTION_TYPE = 'HIDERESP' AND i.USER_ID = u.USER_ID;