/* Formatted on 5/29/2022 11:28:21 AM (QP5 v5.381) */
SELECT *
  FROM IFSAPP.SBL_PAYING_PERCNTG_HIST TT
 WHERE     TT.YEAR = '&YEAR'
       AND TT.PERIOD = '&MONTH'
       AND TT.DISTRICT_CODE LIKE '&DIST_CODE'