select c.order_no,
       c.line_no,
       c.rel_no,
       c.contract,
       c.catalog_no,
       c.catalog_desc,
       c.catalog_type,
       c.real_ship_date,
       c.planned_delivery_date,
       c.wanted_delivery_date,
       c.qty_invoiced,
       c.qty_returned,
       c.qty_shipped,
       c.revised_qty_due,
       --c.fee_code,
       --c.vat,
       c.base_sale_unit_price,
       IFSAPP.customer_order_line_api.Get_Sale_Price_Total(c.order_no,
                                                           c.LINE_NO,
                                                           c.REL_NO,
                                                           c.LINE_ITEM_NO) NSP,
       IFSAPP.CUSTOMER_ORDER_LINE_API.Get_Total_Discount(C.ORDER_NO,
                                                         C.LINE_NO,
                                                         C.REL_NO,
                                                         C.LINE_ITEM_NO) Discount,
       IFSAPP.Customer_Order_Line_API.Get_Total_Tax_Amount(c.order_no,
                                                           c.line_no,
                                                           c.rel_no,
                                                           c.line_item_no) VAT,
       c.demand_order_ref1,
       c.location_no,
       c.job_id,
       c.rowstate
  from customer_order_line_tab c
 where c.contract in ('BSCP',
                      'BLSP',
                      'CLSP', --New Service Center
                      'CSCP',
                      'DSCP',
                      'JSCP',
                      'RSCP',
                      'SSCP',
                      'MS1C',
                      'MS2C',
                      'BTSC')
   and c.rowstate not in ('Cancelled', 'Released')
   and c.demand_order_ref1 is null
   and c.catalog_type = 'INV'
