select E.COMPANY,
       E.ENCASHMENT_ID,
       E.CONTRACT,
       E.ORDER_NO,
       E.AMOUNT,
       E.PAYMENT_DATE,
       E.CHECK_ENCASHMENT_CODE,
       IFSAPP.CHECK_ENCASHMENT_TYPES_API.Get_Description(E.COMPANY,
                                                         E.CHECK_ENCASHMENT_CODE) ENCASHMENT_CODE_DESC,
       E.CUSTOMER_ID,
       E.USER_ID,
       E.BANK_ID,
       IFSAPP.HPNRET_BANK_API.Get_Name(E.BANK_ID) BANK_NAME,
       E.SERIES_ID,
       E.CHECK_NO DOC_REF,
       E.ROWSTATE,
       E.REMARKS
  from IFSAPP.CHECK_ENCASHMENT_TAB E
 WHERE E.CHECK_ENCASHMENT_CODE IN ('CASH-CC', 'EMCC', 'CASH-CC INSTABUY')
   AND E.ROWSTATE = 'Approved'
   AND E.PAYMENT_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
 ORDER BY E.ENCASHMENT_ID
