SELECT H.YEAR,
       H.PERIOD,
       H.ORIGINAL_ACCT_NO,
       H.ACCT_NO,
       H.PRODUCT_CODE,
       TO_CHAR(H.ACTUAL_SALES_DATE, 'MM/DD/YYYY') ACTUAL_SALES_DATE,
       TO_CHAR(H.SALES_DATE, 'MM/DD/YYYY') SALES_DATE,
       TO_CHAR(H.REAL_SHIP_DATE, 'MM/DD/YYYY') REAL_SHIP_DATE,
       TO_CHAR(H.CLOSED_DATE, 'MM/DD/YYYY') CLOSED_DATE,
       H.NORMAL_CASH_PRICE,
       H.HIRE_CASH_PRICE,
       H.HIRE_PRICE,
       H.LIST_PRICE,
       H.BB_NO,
       H.AMOUNT_FINANCED,
       H.MONTHLY_PAY,
       H.FIRST_PAY,
       H.DOWN_PAYMENT,
       H.LOC,
       H.DISCOUNT,H.ARR_AMT,
       H.ACT_OUT_BAL,
       H.VAT,
       TO_CHAR(H.CASH_CONVERSION_ON_DATE, 'MM/DD/YYYY') CASH_CONVERSION_ON_DATE,
       H.CUSTOMER,
       IFSAPP.CUSTOMER_INFO_API.Get_Name(H.CUSTOMER) CUSTOMER_NAME,
       IFSAPP.CUSTOMER_INFO_COMM_METHOD_API.Get_Any_Phone_No(H.CUSTOMER) CUST_PHONE_NO
  FROM IFSAPP.HPNRET_FORM249_ARREARS_TAB H
 WHERE H.YEAR = '&YEAR_I'
   AND H.PERIOD = '&PERIOD'
   AND H.ACT_OUT_BAL > 0
   AND H.SHOP_CODE LIKE '&SHOP_CODE'
 ORDER BY H.SHOP_CODE, H.ORIGINAL_ACCT_NO, H.PRODUCT_CODE