SELECT * FROM SBL_INVENTORY_COUNTING_DTS T
where t.Site = 'CMWH'

/*DELETE FROM SBL_INVENTORY_COUNTING_DTS;
COMMIT;*/

SELECT * FROM SBL_SALES_TEMP_FOR_INVENTORY T
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_SALES_TEMP_FOR_INVENTORY;
COMMIT;*/

select * from SBL_SEND_TEMP_FOR_INVENTORY t
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_SEND_TEMP_FOR_INVENTORY;
COMMIT;*/

select * from SBL_CUT_OFF_FORM_TBL t
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_CUT_OFF_FORM_TBL; 
COMMIT;*/

select * from SBL_CUST_PROD_REPAIR_TAB T
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_CUST_PROD_REPAIR_TAB T;
COMMIT;*/

select * from SBL_UNCLAIM_REPAIR_PRO_TBL T
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_UNCLAIM_REPAIR_PRO_TBL;
COMMIT;*/

SELECT * FROM SBL_SOLD_NOT_DEL_TBL T
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_SOLD_NOT_DEL_TBL;
COMMIT;*/

SELECT * FROM REC_AFTER_CUT_OFF_TBL T
where t.shop_code = 'CKBB'

/*DELETE FROM REC_AFTER_CUT_OFF_TBL;
COMMIT;*/

select * from SBL_REVERT_ACCOUNT_TBL t
where t.shop_code = 'LFNM'

/*DELETE FROM SBL_REVERT_ACCOUNT_TBL;
COMMIT;*/

SELECT * FROM SBL_SHOP_ARRPOVE_TBL T
where t.shop_code = 'LSMB'

/*DELETE FROM SBL_SHOP_ARRPOVE_TBL;
COMMIT;*/

/*DELETE FROM SBL_SHOP_ARRPOVE_TBL T
where t.shop_code = 'MMBB';
COMMIT;*/

/*UPDATE SBL_SHOP_ARRPOVE_TBL T1
SET T1.APPROVE_STATUS = '';
--WHERE t1.shop_code = 'GSGB';
COMMIT;*/

SELECT * FROM SBL_FIXED_ASSET_REGISTER_TAB T
where t.shop_code = 'CKBB'

/*DELETE FROM SBL_FIXED_ASSET_REGISTER_TAB;
COMMIT;*/

select * from SBL_WO_INFO_INVENTORY t
where t.product_site = 'CKBB'

/*DELETE FROM SBL_WO_INFO_INVENTORY;
COMMIT;*/

select * from SBL_PI_SHOP_STOCK_IN_FRANCHISE T
WHERE T.SITE = 'CKBB'

/*DELETE FROM SBL_PI_SHOP_STOCK_IN_FRANCHISE;
COMMIT;*/

select * from SBL_PI_FRANCHISE_INFO t

/*DELETE FROM SBL_PI_FRANCHISE_INFO;
COMMIT;*/

select * from SBL_PI_BANK_CARD_POS t
WHERE T.SHOP_CODE = /*'DPLB'*/ 'DTBB'

/*DELETE FROM SBL_PI_BANK_CARD_POS;
COMMIT;*/

SELECT * FROM IFSAPP.USER_ALLOWED_SITE S

select * from SBL_USER_LIST T
where t.site = 'TUWW'

/*DELETE FROM SBL_USER_LIST;
COMMIT;*/

select * from SBL_PI_SHOP_GPS_INFO t

/*DELETE FROM SBL_PI_SHOP_GPS_INFO;
COMMIT;*/

--***** New [Major Defect]
select * from SBL_PI_DEFECT_LIST t;

/*DELETE FROM SBL_PI_DEFECT_LIST;
COMMIT;*/

select * from SBL_PI_DEFECT_INFO t;

/*DELETE FROM SBL_PI_DEFECT_INFO;
COMMIT;*/


--*****APPROVER PORTAL
select * from SBL_PI_SO_APPROVER t
where t.site = 'KSRB'

/*DELETE FROM SBL_PI_SO_APPROVER;
COMMIT;*/
