SELECT
 SITE,
 CATALOG_NO PART_NO,
  QTY_ONHAND,
 QTY_SALEABLE,
 QTY_DEFECTIVE,
 QTY_REPAIRABLE,
 QTY_UNREPAIRABLE,
 QTY_CUTOFFSALE,
 QTY_SHOP_USE,
 QTY_DENTED,
 
 QTY_BER,
 QTY_SHORT,
 REMARK_SALEABLE,
 REMARK_REPAIRABLE  ,
 REMARK_UNREPAIRABLE,
 REMARK_SHOP_USE ,
 REMARK_DENTED ,
 REMARK_REVERT ,
 REMARK_BER,
  (select sum(QUANTITY)
 from 
  SBL_SEND_TEMP_FOR_INVENTORY M
 where M.SHOP_CODE=S.SITE
 and M.PRODUCT_CODE=S.CATALOG_NO 
 group by SHOP_CODE,PRODUCT_CODE ) QTY_CUT_OFF_SEND,
 (select sum(QUANTITY)
 from 
  SBL_SALES_TEMP_FOR_INVENTORY M
 where M.SHOP_CODE=S.SITE
 and M.PRODUCT_CODE=S.CATALOG_NO 
 group by SHOP_CODE,PRODUCT_CODE ) QTY_CUT_OFF_SALE,
 (select sum(QUANTITY)
 from 
  SBL_REVERT_ACCOUNT_TBL A
 where A.SHOP_CODE=S.SITE
 and A.PRODUCT_CODE=S.CATALOG_NO 
 group by SHOP_CODE,PRODUCT_CODE ) QTY_REVERT
 

  from
IFSAPP.SBL_INVENTORY_COUNTING_DTS  S,
IFSAPP.sbl_product_category_info
WHERE 
 S.CATALOG_NO=IFSAPP.sbl_product_category_info.PRODUCT_CODE
and GROUP_NO like '$product_group'
and SITE like '".$_SESSION["shop_code"]."'
order by CATALOG_NO";
