-- Load Saved GPS Info PHP
SELECT G.REC_ID, G.SITE, G.USER_ID, G.LATITUDE, G.LONGITUDE /*,
       G.ENTRY_DATE,
       G.COUNT_YEAR*/
  FROM IFSAPP.SBL_PI_SHOP_GPS_INFO G
 WHERE G.SITE = '$SHOP_CODE'
   AND G.USER_ID = '$USER_ID'
   AND G.COUNT_YEAR = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));

-- Delete Shop GPS Info PHP
DELETE FROM IFSAPP.SBL_PI_SHOP_GPS_INFO G WHERE G.REC_ID = '$DELETE_ID' AND G.SITE = '$SHOP_CODE';
COMMIT;

-- Find max REC_ID from Table
SELECT MAX(G.REC_ID) AS REC_ID FROM IFSAPP.SBL_PI_SHOP_GPS_INFO G WHERE G.SITE = '$SHOP_CODE';

-- Insert new GPS Info of a Shop
INSERT INTO IFSAPP.SBL_PI_SHOP_GPS_INFO
  (REC_ID, SITE, USER_ID, LATITUDE, LONGITUDE, COUNT_YEAR)
VALUES
  ('$UNI_ID',
   '$SHOP_CODE',
   '$USER_ID',
   '$latitude',
   '$longitude',
   TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')));
COMMIT;
