SELECT 
    (select S.AREA_CODE from SHOP_DTS_INFO S WHERE S.SHOP_CODE = H.SHOP_CODE) AREA_CODE,
    H.SHOP_CODE,
    H.ACCT_NO,
    H.CUSTOMER,
    CUSTOMER_INFO_API.Get_Name(H.CUSTOMER) CUSTOMER_NAME, --CUSTOMER NAME
    CUSTOMER_INFO_API.Get_NIC_No(H.CUSTOMER) NIC, --National ID Card
    H.TEL_NO TELEPHONE_NO,
    CUSTOMER_INFO_ADDRESS_API.Get_Full_Address(H.CUSTOMER, (select T.address_id from CUSTOMER_INFO_ADDRESS t 
      WHERE T.customer_id = H.CUSTOMER)) CUSTOMER_Address,
    TO_CHAR(H.ACTUAL_SALES_DATE, 'MM/DD/YYYY') INVOICE_DATE,
    TO_CHAR(H.SALES_DATE, 'MM/DD/YYYY') SALES_DATE,
    TO_CHAR(H.SALES_DATE + 60, 'MM/DD/YYYY') FIRST_INSTALLMENT_DUE_DATE,
    H.LOC LENGTH_OF_CONTRACT,
    H.EFFECTIVE_RATE,
    H.PRODUCT_CODE,
    H.NORMAL_CASH_PRICE SALES_AMOUNT,
    H.VAT,
    H.NORMAL_CASH_PRICE - (H.HIRE_CASH_PRICE - H.VAT) DISCOUNT,
    (H.NORMAL_CASH_PRICE + H.VAT + H.DISCOUNT) TOTAL_SELLING_PRICE,
    H.DOWN_PAYMENT,
    H.AMOUNT_FINANCED,
    H.TOTAL_UCC,
    (H.LIST_PRICE - (H.HIRE_CASH_PRICE - H.VAT)) OTHER_CHARGES,
    (H.AMOUNT_FINANCED + H.TOTAL_UCC + (H.LIST_PRICE - H.NORMAL_CASH_PRICE)) TOTAL_INSTALLMENT_RECEIVABLE,
    H.MONTHLY_PAY MONTHLY_PAYMENT,
    H.ACT_OUT_BAL,
    H.ARR_AMT ARREAR_AMOUNT,
    CASE WHEN (H.HIRE_PRICE - H.FIRST_PAY - H.ACT_OUT_BAL 
      - ((trunc(MONTHS_BETWEEN(last_day(to_date('&year_i'||'/'||'&PERIOD'||'/1', 'YYYY/MM/DD')), H.ACTUAL_SALES_DATE))
      - 1) * H.MONTHLY_PAY)) <= 0 THEN 0
      ELSE (H.HIRE_PRICE - H.FIRST_PAY - H.ACT_OUT_BAL 
      - ((trunc(MONTHS_BETWEEN(last_day(to_date('&year_i'||'/'||'&PERIOD'||'/1', 'YYYY/MM/DD')), H.ACTUAL_SALES_DATE))
      - 1) * H.MONTHLY_PAY))
      END ADVANCE_AMOUNT,
    TO_CHAR(H.CASH_CONVERSION_ON_DATE, 'MM/DD/YYYY') CASH_CONVERSION_ON_DATE,
    (H.SALES_DATE + (H.LOC * 30)) MATURITY_DATE
FROM HPNRET_FORM249_ARREARS_TAB H
WHERE H.YEAR = '&YEAR_I' AND
  H.PERIOD = '&PERIOD' AND
  --H.SHOP_CODE = 'SESM'
  --H.ACCT_NO = 'ABD-H5502'
  H.ACT_OUT_BAL > 0 --AND
  --trunc(H.CASH_CONVERSION_ON_DATE) < to_date('2014/3/31', 'YYYY/MM/DD') AND
  --H.PRODUCT_CODE LIKE 'HWPHS%'
  --H.ORIGINAL_ACCT_NO = ''
ORDER BY AREA_CODE, H.SHOP_CODE, H.PRODUCT_CODE
