-- Picking line status from WSH_DELIVERY_DETAILS table

SELECT FND.LOOKUP_CODE,
       FND.MEANING
  FROM APPS.FND_LOOKUP_VALUES FND
 WHERE FND.LOOKUP_TYPE='PICK_STATUS'
   AND LANGUAGE ='US'
 ORDER BY lookup_code;

--  Delivery FIRM Status

SELECT FLV.LOOKUP_CODE,
       FLV.MEANING
  FROM APPS.FND_LOOKUP_VALUES FLV
 WHERE FLV.LANGUAGE = 'US'
   AND FLV.LOOKUP_TYPE = 'DELIVERY_PLANNED_FLAG'
 ORDER BY lookup_code;

-- Delivery Status

SELECT FLV.LOOKUP_CODE, 
       FLV.MEANING
  FROM APPS.FND_LOOKUP_VALUES FLV 
 WHERE FLV.LANGUAGE = 'US'
   and flv.lookup_type = 'DELIVERY_STATUS'
 ORDER BY lookup_code;
  
-- WMS TASK status

SELECT *
  FROM APPS.MFG_LOOKUPS
 WHERE LOOKUP_TYPE = 'WMS_TASK_STATUS'
 ORDER BY lookup_code;

-- WMS Task Type

SELECT *
  FROM APPS.MFG_LOOKUPS
 WHERE LOOKUP_TYPE = 'WMS_TASK_TYPES'
 ORDER BY lookup_code;

-- WMS LPN  Context

SELECT *
  FROM APPS.MFG_LOOKUPS
 WHERE LOOKUP_TYPE = 'WMS_LPN_CONTEXT'
 ORDER BY LOOKUP_CODE;

-- Serial Number status

select *
  FROM APPS.MFG_LOOKUPS
 WHERE LOOKUP_TYPE = 'SERIAL_NUM_STATUS'
 order by lookup_code;

-- WIP Job status

SELECT *   FROM APPS.MFG_LOOKUPS  where LOOKUP_TYPE = 'WIP_JOB_STATUS';

SELECT * FROM APPS.MFG_LOOKUPS WHERE LOOKUP_TYPE = 'WIP_SUPPLY'

SELECT * FROM APPS.MFG_LOOKUPS WHERE LOOKUP_TYPE = 'BOM_ITEM_TYPE'

--  Move Order Status

SELECT *
  FROM APPS.MFG_LOOKUPS
 WHERE LOOKUP_TYPE = 'MTL_TXN_REQUEST_STATUS'
order by lookup_code;

-- INV transaction Actions

SELECT *
  FROM APPS.MFG_LOOKUPS
 where lookup_type like 'MTL_TRANSACTION_ACTION';

-- INV transaction Source Type

SELECT *
  FROM APPS.MFG_LOOKUPS
 WHERE lookup_type like 'MTL_TRANSACTION_SOURCE';

-- INV transaction TYPES

SELECT TRANSACTION_TYPE_ID ,
       TRANSACTION_TYPE_NAME ,
       DESCRIPTION
  FROM APPS.MTL_TRANSACTION_TYPES
 ORDER BY 1;