/* Formatted on 2/9/2023 9:36:48 AM (QP5 v5.381) */
  SELECT *
    FROM IFSAPP.HPNRET_RULE
   WHERE 1 = 1
ORDER BY RULE_NO;

SELECT * FROM IFSAPP.HPNRET_RULE_TEMPLATE;

SELECT * FROM IFSAPP.HPNRET_RULE_LINK;

  SELECT *
    FROM IFSAPP.SALES_PRICE_LIST_TAB
   WHERE 1 = 1
ORDER BY ROWVERSION, PRICE_LIST_NO;

SELECT *
  FROM IFSAPP.COMMISSION_AGREE_LINE_TAB CALT;

SELECT *
  FROM IFSAPP.SALES_PRICE_LIST_PART_TAB SPLPT;

SELECT * FROM IFSAPP.SALES_PRICE_LIST;

SELECT * FROM IFSAPP.SALES_PART_BASE_PRICE;


SELECT *
  FROM IFSAPP.SBL_DISCOUNT_PROMOTION SDP;


SELECT *
  FROM IFSAPP.SALES_PRICE_LIST_PART SPLP
 WHERE 1 = 1 AND PERCENTAGE_OFFSET > 0;


SELECT *
  FROM IFSAPP.SBL_LATEST_PRICE_LIST SLPL
 WHERE ROWNUM < 3;