/* Formatted on 8/26/2021 10:42:07 AM (QP5 v5.287) */
EXEC AD_ZD_MVIEW.UPGRADE('APPS','XXDBLCL_SALES_ORDER_DTL_MV');

GRANT SELECT ON APPS.XXDBLCL_SALES_ORDER_DTL_MV TO APPSRO;

GRANT SELECT ON APPS.XXDBLCL_SALES_ORDER_DTL_MV# TO APPSRO;