select B.BUDGET_BOOK_ID,
       B.DESCRIPTION,
       B.FROM_DATE,
       B.TO_DAT               TO_DATE,
       B.MINIMUM_DOWN_PAYMENT "MINIMUM_DOWN_PAYMENT%", 
       B.INTEREST "INTEREST_RATE%", 
       B.START_VALUE,
       B.END_VALUE,
       B.DURATION TIME_DURATION,
       B.PAYMENT_TERM_FROM,
       B.PAYMENT_TERM_TO,
       B.HPNRET_BB_SALES_TYPE SALES_TYPE,
       B.HPNRET_BB_TYPE BB_TYPE,
       B.INCLUDE_SERVICE_CHG ENABLE_SERVICE_CHARGE,
       B.ROWSTATE,
       B.GRACE_PERIOD
  from HPNRET_BB_MAIN_HEAD_TAB B
  ORDER BY B.FROM_DATE
