SELECT   H.YEAR,
         H.PERIOD,
         /*H.SHOP_CODE,
         H.ACCT_NO,
         H.MONTHLY_PAY,
         H.ACT_OUT_BAL,
         H.EFFECTIVE_RATE,
         H.PRESENT_VALUE,
         H.ACTUAL_UCC,*/
         SUM(IFSAPP.GET_SBL_M1_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_1,
         SUM(IFSAPP.GET_SBL_M2_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_2,
         SUM(IFSAPP.GET_SBL_M3_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_3,
         SUM(IFSAPP.GET_SBL_M4_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_4,
         SUM(IFSAPP.GET_SBL_M5_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_5,
         SUM(IFSAPP.GET_SBL_M6_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_6,
         SUM(IFSAPP.GET_SBL_M7_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_7,
         SUM(IFSAPP.GET_SBL_M8_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_8,
         SUM(IFSAPP.GET_SBL_M9_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_9,
         SUM(IFSAPP.GET_SBL_M10_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_10,
         SUM(IFSAPP.GET_SBL_M11_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_11,
         SUM(IFSAPP.GET_SBL_M12_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO)) TOTAL_MONTH_12
FROM     HPNRET_FORM249_ARREARS_TAB H
WHERE    H.YEAR = '&YEAR_I' 
AND      H.PERIOD = '&PERIOD' 
AND      H.ACT_OUT_BAL > 0
--AND      H.ACCT_NO != 'SES-H320'
AND      H.PRESENT_VALUE IS NOT NULL
AND      H.EFFECTIVE_RATE IS NOT NULL
AND      H.MONTHLY_PAY > 0
GROUP BY H.YEAR, H.PERIOD
