SELECT H.YEAR,
       H.PERIOD,
       H.SHOP_CODE,
       H.ACCT_NO,
       H.MONTHLY_PAY,
       H.ACT_OUT_BAL,
       H.EFFECTIVE_RATE,
       H.PRESENT_VALUE,
       H.ACTUAL_UCC,
       IFSAPP.GET_SBL_M1_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_1,
       IFSAPP.GET_SBL_M2_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_2,
       IFSAPP.GET_SBL_M3_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_3,
       IFSAPP.GET_SBL_M4_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_4,
       IFSAPP.GET_SBL_M5_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_5,
       IFSAPP.GET_SBL_M6_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_6,
       IFSAPP.GET_SBL_M7_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_7,
       IFSAPP.GET_SBL_M8_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_8,
       IFSAPP.GET_SBL_M9_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_9,
       IFSAPP.GET_SBL_M10_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_10,
       IFSAPP.GET_SBL_M11_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_11,
       IFSAPP.GET_SBL_M12_ECC_F_AGING(H.YEAR, H.PERIOD, H.ACCT_NO) MONTH_12
FROM   HPNRET_FORM249_ARREARS_TAB H
WHERE  H.YEAR = '&YEAR_I' 
AND    H.PERIOD = '&PERIOD' 
AND    H.ACT_OUT_BAL > 0
