/* Formatted on 5/29/2022 2:01:51 PM (QP5 v5.381) */
SELECT s.SALES_RETURN_NO,
       s.CONTRACT,
       s.DATE_REQUESTED,
       s.CUSTOMER_NO,
       (SELECT DISTINCT r.ORDER_NO
          FROM IFSAPP.HPNRET_SALES_RET_LINE R
         WHERE r.SALES_RETURN_NO = s.SALES_RETURN_NO)    ORDER_NO
  FROM ifsapp.HPNRET_SALES_RETURN_TAB s
 WHERE     s.REFUN_STMT_ID IS NULL
       AND (SELECT DISTINCT r.ORDER_NO
              FROM IFSAPP.HPNRET_SALES_RET_LINE R
             WHERE r.SALES_RETURN_NO = s.SALES_RETURN_NO)
               IS NOT NULL