--Datewise Product Family Sales Summary (Retail)
SELECT R.SALES_DATE,
       P.PRODUCT_FAMILY,
       SUM(R.SALES_QUANTITY) SALES_QUANTITY,
       SUM(R.SALES_PRICE) REVENUE
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW R,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    P
 WHERE R.PRODUCT_CODE = P.PRODUCT_CODE
   AND R.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
   AND R.SALES_PRICE != 0
   AND P.PRODUCT_FAMILY IN ('COMPUTER-DESKTOP', 'COMPUTER-LAPTOP')
 GROUP BY R.SALES_DATE,
          P.PRODUCT_FAMILY
 ORDER BY R.SALES_DATE,
          P.PRODUCT_FAMILY
