SELECT R.SALES_DATE,
       P.PRODUCT_FAMILY,
       SUM(R.SALES_QUANTITY) SALES_QUANTITY,
       SUM(R.SALES_PRICE) REVENUE
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW R,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    P
 WHERE R.PRODUCT_CODE = P.PRODUCT_CODE
   AND R.SALES_PRICE != 0
   AND R.SALES_DATE BETWEEN $P{FROM_DATE} AND $P{TO_DATE} 
   AND $X{IN, P.PRODUCT_FAMILY, PRODUCT_FAMILY}
 GROUP BY R.SALES_DATE,
          P.PRODUCT_FAMILY
 ORDER BY R.SALES_DATE,
          P.PRODUCT_FAMILY
