--Multi-Brand Sales Summary Shopwise
SELECT R.SHOP_CODE,
       R.AREA_CODE,
       R.DISTRICT_CODE,
       SUM(R.SALES_PRICE) TOTAL_SALES_PRICE,
       SUM(R.AMOUNT_RSP) TOTAL_AMOUNT_RSP
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW R,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    P
 WHERE R.PRODUCT_CODE = P.PRODUCT_CODE
   AND R.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
   AND P.BRAND NOT IN ('Singer', 'Merritt', 'Singtech', 'Sinotec')
   AND P.PRODUCT_FAMILY NOT IN ( /*'MONITOR',*/ 'GIFT', 'Raw Material') /*= 'COMPUTER-DESKTOP'*/
   AND P.PRODUCT_CODE != 'SGCOM-LED-18.5'
 GROUP BY R.SHOP_CODE, R.AREA_CODE, R.DISTRICT_CODE
 ORDER BY TO_NUMBER(R.DISTRICT_CODE), R.SHOP_CODE
