--*****Retail Refrigerator Sales
SELECT 'RETAIL' Sales_Channel,
       'REFRIGERATOR' PRODUCT_GROUP,
       TO_CHAR(TO_DATE('&FROM_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') || ' to ' ||
       TO_CHAR(TO_DATE('&TO_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') DATE_RANGE,
       SUM(IPV.SALES_QUANTITY) TOTAL_SALES_QUANTITY,
       SUM(IPV.SALES_PRICE) TOTAL_SALES_PRICE
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW IPV,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    DI
 WHERE IPV.PRODUCT_CODE = DI.PRODUCT_CODE
   AND IPV.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
   AND DI.PRODUCT_FAMILY IN ('REFRIGERATOR-DIRECT-COOL',
                             'REFRIGERATOR-SIDE-BY-SIDE',
                             'REFRIGERATOR-NOFROST')

UNION ALL

--*****Retail Freezer Sales
SELECT 'RETAIL' Sales_Channel,
       'FREEZER' PRODUCT_GROUP,
       TO_CHAR(TO_DATE('&FROM_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') || ' to ' ||
       TO_CHAR(TO_DATE('&TO_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') DATE_RANGE,
       SUM(IPV.SALES_QUANTITY) TOTAL_SALES_QUANTITY,
       SUM(IPV.SALES_PRICE) TOTAL_SALES_PRICE
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW IPV,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    DI
 WHERE IPV.PRODUCT_CODE = DI.PRODUCT_CODE
   AND IPV.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
   AND DI.PRODUCT_FAMILY IN ('REFRIGERATOR-FREEZER',
                             'REFRIGERATOR-SEMI-COMM')

UNION ALL

--*****Wholesale Refrigerator Sales
SELECT 'WHOLESALE' Sales_Channel,
       'REFRIGERATOR' PRODUCT_GROUP,
       TO_CHAR(TO_DATE('&FROM_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') || ' to ' ||
       TO_CHAR(TO_DATE('&TO_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') DATE_RANGE,
       SUM(B.TOTAL_SALES_QUANTITY) TOTAL_SALES_QUANTITY,
       SUM(B.TOTAL_SALES_PRICE) TOTAL_SALES_PRICE
  FROM (SELECT SUM(W.SALES_QUANTITY) TOTAL_SALES_QUANTITY,
               SUM(W.SALES_PRICE) TOTAL_SALES_PRICE
          FROM ifsapp.sbl_vw_wholesale_sales  W,
               IFSAPP.SBL_JR_PRODUCT_DTL_INFO DI
         WHERE W.PRODUCT_CODE = DI.Product_Code
           AND W.SITE in ('JWSS', 'SAOS', 'SWSS', 'WSMO', 'SCSM')
           AND W.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
               TO_DATE('&TO_DATE', 'YYYY/MM/DD')
           AND DI.PRODUCT_FAMILY IN
               ('REFRIGERATOR-DIRECT-COOL',
                'REFRIGERATOR-SIDE-BY-SIDE',
                'REFRIGERATOR-NOFROST')
        UNION ALL
        select SUM(S.SALES_QUANTITY) SALES_QUANTITY,
               SUM(S.SALES_PRICE) SALES_PRICE
          from IFSAPP.SBL_JR_SALES_DTL_INV    S,
               IFSAPP.SBL_JR_PRODUCT_DTL_INFO DI
         WHERE S.PRODUCT_CODE = DI.PRODUCT_CODE
           AND S.SITE IN ('SAPM', 'SESM', 'SHOM', 'SISM', 'SFSM', 'SOSM')
           AND S.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
               TO_DATE('&TO_DATE', 'YYYY/MM/DD')
           AND DI.PRODUCT_FAMILY IN
               ('REFRIGERATOR-DIRECT-COOL',
                'REFRIGERATOR-SIDE-BY-SIDE',
                'REFRIGERATOR-NOFROST')) B

UNION ALL

--*****Wholesale Freezer Sales
SELECT 'WHOLESALE' Sales_Channel,
       'FREEZER' PRODUCT_GROUP,
       TO_CHAR(TO_DATE('&FROM_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') || ' to ' ||
       TO_CHAR(TO_DATE('&TO_DATE', 'YYYY/MM/DD'), 'YYYY/MM/DD') DATE_RANGE,
       SUM(C.TOTAL_SALES_QUANTITY) TOTAL_SALES_QUANTITY,
       SUM(C.TOTAL_SALES_PRICE) TOTAL_SALES_PRICE
  FROM (SELECT SUM(W.SALES_QUANTITY) TOTAL_SALES_QUANTITY,
               SUM(W.SALES_PRICE) TOTAL_SALES_PRICE
          FROM ifsapp.sbl_vw_wholesale_sales  W,
               IFSAPP.SBL_JR_PRODUCT_DTL_INFO DI
         WHERE W.PRODUCT_CODE = DI.Product_Code
           AND W.SITE in ('JWSS', 'SAOS', 'SWSS', 'WSMO', 'SCSM')
           AND W.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
               TO_DATE('&TO_DATE', 'YYYY/MM/DD')
           AND DI.PRODUCT_FAMILY IN
               ('REFRIGERATOR-FREEZER', 'REFRIGERATOR-SEMI-COMM')
        UNION ALL
        select SUM(S.SALES_QUANTITY) SALES_QUANTITY,
               SUM(S.SALES_PRICE) SALES_PRICE
          from IFSAPP.SBL_JR_SALES_DTL_INV    S,
               IFSAPP.SBL_JR_PRODUCT_DTL_INFO DI
         WHERE S.PRODUCT_CODE = DI.PRODUCT_CODE
           AND S.SITE IN ('SAPM', 'SESM', 'SHOM', 'SISM', 'SFSM', 'SOSM')
           AND S.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
               TO_DATE('&TO_DATE', 'YYYY/MM/DD')
           AND DI.PRODUCT_FAMILY IN
               ('REFRIGERATOR-FREEZER', 'REFRIGERATOR-SEMI-COMM')) C                           
