CREATE OR REPLACE VIEW SBL_JR_NATIONAL_INV_VIEW AS
SELECT I.CONTRACT,
       I.PART_NO,
       IFSAPP.INVENTORY_PRODUCT_FAMILY_API.GET_DESCRIPTION(IFSAPP.INVENTORY_PART_API.GET_PART_PRODUCT_FAMILY('SCOM',
                                                                                                             I.PART_NO)) PRODUCT_GROUP,
       SUM(I.QTY_ONHAND) QTY_ONHAND,
       'SERVICE_CENTER' INV_CHANNEL
  FROM IFSAPP.INVENTORY_PART_IN_STOCK I
 WHERE I.QTY_ONHAND > 0
   AND IFSAPP.INVENTORY_PART_API.GET_PART_PRODUCT_FAMILY('SCOM', I.PART_NO) !=
       'RBOOK'
   AND IFSAPP.INVENTORY_PART_API.GET_PART_PRODUCT_CODE('SCOM', I.PART_NO) !=
       'RAW'
   AND IFSAPP.INVENTORY_PART_API.GET_SECOND_COMMODITY('SCOM', I.PART_NO) NOT LIKE
       'S-%'
   AND I.CONTRACT IN ('BSCP',
                      'BLSP',
                      'CLSP',
                      'CSCP',
                      'CXSP', --New Service Center
                      'DSCP',
                      'MSCP', --New Service Center
                      'JSCP',
                      'RPSP', --New Service Center
                      'RSCP',
                      'SSCP',
                      'MS1C',
                      'MS2C',
                      'BTSC')
 GROUP BY I.CONTRACT, I.PART_NO

UNION ALL

--FOR WAREHOUSE INVENTORY
SELECT WI.WARE_HOUSE_NAME CONTRACT,
       IP.PART_NO,
       PDI.PRODUCT_FAMILY PRODUCT_GROUP,
       SUM(IP.QTY_ONHAND) QTY_ONHAND,
       'WAREHOUSE' INV_CHANNEL
  FROM IFSAPP.INVENTORY_PART_IN_STOCK IP,
       SBL_JR_PRODUCT_DTL_INFO        PDI,
       IFSAPP.WARE_HOUSE_INFO         WI
 WHERE WI.WARE_HOUSE_NAME = IP.CONTRACT
   AND IP.PART_NO = PDI.PRODUCT_CODE
   AND IP.QTY_ONHAND > 0
 GROUP BY WI.WARE_HOUSE_NAME, IP.PART_NO, PDI.PRODUCT_FAMILY

UNION ALL

--FOR ON-TRANSIT INV
SELECT TT.CONTRACT,
       TT.PART_NO,
       DI.PRODUCT_FAMILY PRODUCT_GROUP,
       SUM(TT.QTY) QTY_ONHAND,
       'ON_TRANSIT' INV_CHANNEL
  FROM INV_TRANSIT_TRACKING TT, SBL_JR_PRODUCT_DTL_INFO DI
 WHERE TT.QTY > 0
   AND TT.PART_NO = DI.PRODUCT_CODE
 GROUP BY TT.CONTRACT, TT.PART_NO, DI.PRODUCT_FAMILY

UNION ALL

--FOR RETAIL SHOP INV
SELECT AA.CONTRACT,
       AA.PART_NO,
       DI.PRODUCT_FAMILY PRODUCT_GROUP,
       SUM(AA.QTY_ONHAND) QTY_ONHAND,
       'SHOP' INV_CHANNEL
  FROM IFSAPP.INVENTORY_PART_IN_STOCK AA,
       SBL_JR_PRODUCT_DTL_INFO        DI,
       SHOP_DTS_INFO                  SDI
 WHERE SDI.SHOP_CODE = AA.CONTRACT
   AND AA.PART_NO = DI.PRODUCT_CODE
   AND AA.QTY_ONHAND > 0
 GROUP BY AA.CONTRACT, AA.PART_NO, DI.PRODUCT_FAMILY;
