--Shopwise Product Model Sales Details (Date Range)
SELECT R.SHOP_CODE,
       R.AREA_CODE,
       R.DISTRICT_CODE,
       R.ORDER_NO,
       R.SALES_DATE,
       R.Status,
       R.PRODUCT_CODE,
       P.PRODUCT_FAMILY,
       P.BRAND,
       R.SALES_QUANTITY,
       R.SALES_PRICE,
       R
       ifsapp.customer_info_api.Get_Name(R.CUSTOMER_NO) customer_name,
       ifsapp.CUSTOMER_INFO_COMM_METHOD_API.Get_Any_Phone_No(R.CUSTOMER_NO) phone_no,
       IFSAPP.CUSTOMER_INFO_ADDRESS_API.Get_Address1(R.CUSTOMER_NO, 1) || ' ' ||
       IFSAPP.CUSTOMER_INFO_ADDRESS_API.Get_Address2(R.CUSTOMER_NO, 1) customer_address
  FROM IFSAPP.SBL_JR_SALES_INV_COMP_VIEW R,
       IFSAPP.SBL_JR_PRODUCT_DTL_INFO    P
 WHERE R.PRODUCT_CODE = P.PRODUCT_CODE
   AND R.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
   AND R.SALES_PRICE != 0
   /*AND P.PRODUCT_FAMILY \*IN ('COMPUTER-DESKTOP', 'COMPUTER-LAPTOP', 'COMPUTER-ACCESSORIES')*\ \*= 'TV-PANEL'*\*/
   AND P.BRAND = 'Samsung'
   /*AND P.PRODUCT_CODE in ('SRREF-SFB340WB',
                          'SRREF-SFT340WB',
                          'SRREF-SFT360WB',
                          'SRREF-SFT440WB',
                          'SRREF-SFT470WB')*/ /*= 'SRSM-SME-1408' LIKE '%FUR-%'*/
   /*AND P.COMMODITY_GROUP2 IN
       ('GRUNDIG-KITCHEN APPLIANCES',
        'PHILIPS-KITCHEN APPLIANCE',
        'PREETHI-KITCHEN APPLIANCES',
        'SEBEC-KITCHEN APPLIANCES',
        'SIEMENS-KITCHEN APPLIANCES',
        'SINGER-KITCHEN APPLIANCES',
        'PRESTIGE-PRESSURE COOKER')*/ --Small Appliances
   /*AND R.DISTRICT_CODE = 20*/
 ORDER BY TO_NUMBER(R.DISTRICT_CODE), R.ORDER_NO

--*****Parameter Values
--Product Family
/*'REFRIGERATOR-DIRECT-COOL',
'REFRIGERATOR-SIDE-BY-SIDE',
'REFRIGERATOR-NOFROST',
'REFRIGERATOR-FREEZER',
'REFRIGERATOR-SEMI-COMM',
'TV-PANEL'
'OVEN-ELECTRICWAVE'
'OVEN-MICROWAVE'
'WASHING-MACHINE-TOP-LOADER'
'RICE-COOKER'
'COMPUTER-DESKTOP'
'COMPUTER-LAPTOP'*/

--Brand
/*Samsung
Beko
Pureit*/

--Part No
/*SRSM-SME-1408
SRREF-SINGER-RD-32WR
SRREF-SINGER-RD-43WR
SRSM-SS-HEAD-15CH1
SRTV-SLE23D1200TC
*/
