SELECT MM.AREA_CODE,
       MM.DISTRICT_CODE,
       KK.SHOP_CODE,
       KK.TARGET_REVENUE,
       NVL(MM.ACHIEVEMENT, 0) ACHIEVEMENT,
       CASE
         WHEN KK.TARGET_REVENUE < 0 THEN
          0
         ELSE
          (MM.ACHIEVEMENT / KK.TARGET_REVENUE) * 100
       END ACHIEV_PRCNTG
  FROM (SELECT AA.SHOP_CODE, SUM(AA.REVENUE) TARGET_REVENUE
          FROM IFSAPP.SBL_JR_RST_REVENUE_TGT AA
         WHERE AA.PERIOD BETWEEN '&START_PERIOD' AND '&END_PERIOD'
           AND AA.YEAR = '&YEAR_I'
         GROUP BY AA.SHOP_CODE
         ORDER BY AA.SHOP_CODE) KK
  LEFT JOIN (SELECT BB.AREA_CODE,
                    BB.DISTRICT_CODE,
                    BB.SHOP_CODE,
                    SUM(BB.SALES_PRICE) ACHIEVEMENT
               FROM IFSAPP.SBL_JR_SALES_INV_PKG_VIEW BB
              WHERE EXTRACT(MONTH FROM BB.SALES_DATE) BETWEEN
                    '&START_PERIOD' AND '&END_PERIOD'
                AND EXTRACT(YEAR FROM BB.SALES_DATE) = '&YEAR_I'
              GROUP BY BB.AREA_CODE, BB.DISTRICT_CODE, BB.SHOP_CODE
              ORDER BY BB.AREA_CODE, BB.DISTRICT_CODE, BB.SHOP_CODE) MM
    ON KK.SHOP_CODE = MM.SHOP_CODE
 WHERE MM.AREA_CODE IN '&AREA_CODE'
 ORDER BY TO_NUMBER(MM.DISTRICT_CODE, 99), KK.SHOP_CODE /*MM.AREA_CODE*/
