SELECT H.YEAR,
       H.PERIOD,
       H.SHOP_CODE,
       H.ACCT_NO,
       H.PRODUCT_CODE,
       TO_CHAR(H.ACTUAL_SALES_DATE, 'MM/DD/YYYY') ACTUAL_SALES_DATE,
       IFSAPP.CUSTOMER_INFO_API.Get_Name(H.CUSTOMER) CUSTOMER_NAME,
       REPLACE(H.TEL_NO, ',', '_') TEL_NO,
       IFSAPP.CUSTOMER_INFO_API.Get_NIC_No(H.CUSTOMER) NIC_NO,
       H.MONTHLY_PAY,
       H.ACT_OUT_BAL,
       H.COLLECTION COLLECTION_AMT,
       H.ARR_AMT--,
       /*ifsapp.get_sbl_del_amt(H.YEAR, H.PERIOD, H.ACCT_NO) DEL_AMT*/
  FROM ifsapp.HPNRET_FORM249_ARREARS_TAB H
 WHERE H.YEAR = '&YEAR'
   AND H.PERIOD = '&PERIOD'
   AND H.SHOP_CODE LIKE '&SHOP_CODE'
   AND H.ACT_OUT_BAL > 0
 ORDER BY H.SHOP_CODE, H.ACCT_NO
