/* Formatted on 12/7/2021 10:11:39 AM (QP5 v5.365) */
CREATE TABLE MVIEW_TEST
(
    NO      NUMBER PRIMARY KEY,
    NAME    VARCHAR2 (10)
);

CREATE MATERIALIZED VIEW TEST_MV1
AS
    SELECT * FROM MVIEW_TEST;

CREATE MATERIALIZED VIEW TEST_MV2
AS
    SELECT * FROM TEST_MV1;

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'TEST_MV%' AND OBJECT_TYPE = 'MATERIALIZED VIEW';
 
 
 INSERT INTO MVIEW_TEST VALUES (1,'A');
COMMIT;

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'TEST_MV%' AND OBJECT_TYPE = 'MATERIALIZED VIEW';
 
 
 EXEC DBMS_MVIEW.REFRESH('TEST_MV1');
 
 SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'TEST_MV%' AND OBJECT_TYPE = 'MATERIALIZED VIEW';
 
 ALTER TABLE MVIEW_TEST ADD (CITY VARCHAR2(10));
 
 SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'TEST_MV%' AND OBJECT_TYPE = 'MATERIALIZED VIEW';
 
 
 DROP TABLE MVIEW_TEST PURGE;
 
 
 SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME LIKE 'TEST_MV%' AND OBJECT_TYPE = 'MATERIALIZED VIEW';