/* Formatted on 6/13/2021 10:26:38 AM (QP5 v5.287) */
CREATE MATERIALIZED VIEW APPS.XXDBL_INV_CON_REPORT_MVIEW
(
   REPORT_TYPE,
   SET_OF_BOOKS_ID,
   ORGANIZATION_ID,
   ORGANIZATION_NAME,
   TR_TYPE,
   TRANSACTION_ID,
   TRANSACTION_DATE,
   MO_NO,
   ITEM_CODE,
   ITEM_DESCRIPTION,
   UOM,
   ITEM_CATEGORY,
   ITEM_TYPE,
   DEPARTMENT,
   USE_AREA,
   NATURAL_ACC,
   COMPANY_CODE,
   LOCATION_DESC,
   PRODUCT_LINE_DESC,
   COST_CENTER_DESC,
   NATURAL_ACCOUNT_DESC,
   SUB_ACCCOUNT_DESC,
   INTER_COMPANY,
   EXP_CATEGORY_DESC,
   CODE_COMBINATION,
   QTY,
   UNIT_COST,
   TOTAL_COST,
   BUYER_NAME,
   CUSTOMER_NAME,
   ASSET_DESCRIPTION,
   CREATED_BY
)
   TABLESPACE APPS_TS_SUMMARY
   PCTUSED 0
   PCTFREE 10
   INITRANS 10
   MAXTRANS 255
   STORAGE (INITIAL 16 K
            NEXT 64 K
            MAXSIZE UNLIMITED
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOCACHE
   LOGGING
   NOCOMPRESS
   NOPARALLEL
   BUILD DEFERRED
   USING INDEX
      TABLESPACE APPS_TS_SUMMARY
      PCTFREE 10
      INITRANS 11
      MAXTRANS 255
      STORAGE (INITIAL 16 K
               NEXT 64 K
               MINEXTENTS 1
               MAXEXTENTS UNLIMITED
               PCTINCREASE 0
               BUFFER_POOL DEFAULT
               FLASH_CACHE DEFAULT
               CELL_FLASH_CACHE DEFAULT)
   REFRESH
      FORCE
      ON DEMAND
      WITH PRIMARY KEY
AS
   SELECT "ICR"."REPORT_TYPE" "REPORT_TYPE",
          "ICR"."SET_OF_BOOKS_ID" "SET_OF_BOOKS_ID",
          "ICR"."ORGANIZATION_ID" "ORGANIZATION_ID",
          "ICR"."ORGANIZATION_NAME" "ORGANIZATION_NAME",
          "ICR"."TR_TYPE" "TR_TYPE",
          "ICR"."TRANSACTION_ID" "TRANSACTION_ID",
          "ICR"."TRANSACTION_DATE" "TRANSACTION_DATE",
          "ICR"."MO_NO" "MO_NO",
          "ICR"."ITEM_CODE" "ITEM_CODE",
          "ICR"."ITEM_DESCRIPTION" "ITEM_DESCRIPTION",
          "ICR"."UOM" "UOM",
          "ICR"."ITEM_CATEGORY" "ITEM_CATEGORY",
          "ICR"."ITEM_TYPE" "ITEM_TYPE",
          "ICR"."DEPARTMENT" "DEPARTMENT",
          "ICR"."USE_AREA" "USE_AREA",
          "ICR"."NATURAL_ACC" "NATURAL_ACC",
          "ICR"."COMPANY_CODE" "COMPANY_CODE",
          "ICR"."LOCATION_DESC" "LOCATION_DESC",
          "ICR"."PRODUCT_LINE_DESC" "PRODUCT_LINE_DESC",
          "ICR"."COST_CENTER_DESC" "COST_CENTER_DESC",
          "ICR"."NATURAL_ACCOUNT_DESC" "NATURAL_ACCOUNT_DESC",
          "ICR"."SUB_ACCCOUNT_DESC" "SUB_ACCCOUNT_DESC",
          "ICR"."INTER_COMPANY" "INTER_COMPANY",
          "ICR"."EXP_CATEGORY_DESC" "EXP_CATEGORY_DESC",
          "ICR"."CODE_COMBINATION" "CODE_COMBINATION",
          "ICR"."QTY" "QTY",
          "ICR"."UNIT_COST" "UNIT_COST",
          "ICR"."TOTAL_COST" "TOTAL_COST",
          "ICR"."BUYER_NAME" "BUYER_NAME",
          "ICR"."CUSTOMER_NAME" "CUSTOMER_NAME",
          "ICR"."ASSET_DESCRIPTION" "ASSET_DESCRIPTION",
          "ICR"."CREATED_BY" "CREATED_BY"
     FROM "APPS"."XXDBL_INV_CON_RPT" "ICR";