/* Formatted on 4/28/2021 3:00:50 PM (QP5 v5.287) */
CREATE MATERIALIZED VIEW APPS.XXDBL_INV_MTRL_MV
(
   TRANSACTION_ID,
   TRANSACTION_DATE,
   ORGANIZATION_ID,
   INVENTORY_ITEM_ID,
   SUBINVENTORY_CODE,
   TRANSACTION_TYPE_ID,
   TRANSACTION_TYPE_NAME,
   TRANSACTION_SOURCE_ID,
   TRANSACTION_SOURCE_TYPE_ID,
   TRANSACTION_ACTION_ID,
   TRANSACTION_QUANTITY,
   TRANSACTION_UOM,
   PRIMARY_QUANTITY,
   SECONDARY_UOM_CODE,
   SECONDARY_TRANSACTION_QUANTITY
)
   TABLESPACE APPS_TS_SUMMARY
   PCTUSED 0
   PCTFREE 10
   INITRANS 10
   MAXTRANS 255
   STORAGE (INITIAL 16 K
            NEXT 64 K
            MAXSIZE UNLIMITED
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOCACHE
   LOGGING
   NOCOMPRESS
   NOPARALLEL
   BUILD DEFERRED
   USING INDEX
      TABLESPACE APPS_TS_SUMMARY
      PCTFREE 10
      INITRANS 11
      MAXTRANS 255
      STORAGE (INITIAL 16 K
               NEXT 64 K
               MINEXTENTS 1
               MAXEXTENTS UNLIMITED
               PCTINCREASE 0
               BUFFER_POOL DEFAULT
               FLASH_CACHE DEFAULT
               CELL_FLASH_CACHE DEFAULT)
   REFRESH
      FORCE
      ON DEMAND
      WITH PRIMARY KEY
AS
   SELECT "MMT"."TRANSACTION_ID",
          "MMT"."TRANSACTION_DATE",
          "MMT"."ORGANIZATION_ID",
          "MMT"."INVENTORY_ITEM_ID",
          "MMT"."SUBINVENTORY_CODE",
          "MMT"."TRANSACTION_TYPE_ID",
          "MTT"."TRANSACTION_TYPE_NAME",
          "MMT"."TRANSACTION_SOURCE_ID",
          "MMT"."TRANSACTION_SOURCE_TYPE_ID",
          "MMT"."TRANSACTION_ACTION_ID",
          "MMT"."TRANSACTION_QUANTITY",
          "MMT"."TRANSACTION_UOM",
          "MMT"."PRIMARY_QUANTITY",
          "MMT"."SECONDARY_UOM_CODE",
          "MMT"."SECONDARY_TRANSACTION_QUANTITY"
     FROM "INV"."MTL_MATERIAL_TRANSACTIONS" "MMT",
          "INV"."MTL_TRANSACTION_TYPES" "MTT"
    WHERE     "MMT"."TRANSACTION_TYPE_ID" = "MTT"."TRANSACTION_TYPE_ID";