/* Formatted on 4/28/2021 11:29:05 AM (QP5 v5.287) */
CREATE MATERIALIZED VIEW APPS.XXDBL_INV_CON_RPT_MV
(
   TRANSACTION_ID,
   ITEM_CODE,
   ITEM_DESCRIPTION,
   UOM,
   ITEM_CATEGORY,
   ITEM_TYPE,
   TRX_QUANTITY
)
   TABLESPACE APPS_TS_SUMMARY
   PCTUSED 0
   PCTFREE 10
   INITRANS 10
   MAXTRANS 255
   STORAGE (INITIAL 16 K
            NEXT 64 K
            MAXSIZE UNLIMITED
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOCACHE
   LOGGING
   NOCOMPRESS
   NOPARALLEL
   BUILD DEFERRED
   USING INDEX
      TABLESPACE APPS_TS_SUMMARY
      PCTFREE 10
      INITRANS 11
      MAXTRANS 255
      STORAGE (INITIAL 16 K
               NEXT 64 K
               MINEXTENTS 1
               MAXEXTENTS UNLIMITED
               PCTINCREASE 0
               BUFFER_POOL DEFAULT
               FLASH_CACHE DEFAULT
               CELL_FLASH_CACHE DEFAULT)
   REFRESH
      FORCE
      ON DEMAND
      WITH PRIMARY KEY
AS
   SELECT "A"."TRANSACTION_ID" "TRANSACTION_ID",
          "C"."SEGMENT1" "ITEM_CODE",
          "C"."DESCRIPTION" "ITEM_DESCRIPTION",
          "C"."PRIMARY_UOM_CODE" "UOM",
          "MIC"."SEGMENT2" "ITEM_CATEGORY",
          "MIC"."SEGMENT3" "ITEM_TYPE",
          "A"."PRIMARY_QUANTITY" "TRX_QUANTITY"
     FROM "APPS"."MTL_MATERIAL_TRANSACTIONS" "A",
          "APPS"."MTL_TXN_REQUEST_HEADERS" "B",
          "APPS"."MTL_TXN_REQUEST_LINES_V" "MTRL",
          "APPS"."MTL_SYSTEM_ITEMS_B_KFV" "C",
          "APPS"."MTL_ITEM_CATEGORIES_V" "MIC",
          "APPS"."GL_CODE_COMBINATIONS" "CC",
          "APPS"."MTL_PARAMETERS" "MP",
          "APPS"."ORG_ORGANIZATION_DEFINITIONS" "OOD",
          "APPS"."HR_OPERATING_UNITS" "HOU",
          "APPS"."ORG_ACCT_PERIODS" "PRD",
          "APPS"."FND_USER" "FNU"
    WHERE     "A"."ORGANIZATION_ID" = "MP"."ORGANIZATION_ID"
          AND "MP"."ORGANIZATION_ID" = "OOD"."ORGANIZATION_ID"
          AND "OOD"."OPERATING_UNIT" = "HOU"."ORGANIZATION_ID"
          AND "A"."INVENTORY_ITEM_ID" = "C"."INVENTORY_ITEM_ID"
          AND "A"."ORGANIZATION_ID" = "C"."ORGANIZATION_ID"
          AND "A"."INVENTORY_ITEM_ID" = "MIC"."INVENTORY_ITEM_ID"
          AND "A"."ORGANIZATION_ID" = "MIC"."ORGANIZATION_ID"
          AND "A"."TRANSACTION_SOURCE_ID" = "B"."HEADER_ID"
          AND "B"."HEADER_ID" = "MTRL"."HEADER_ID"
          AND "B"."CREATED_BY" = "FNU"."USER_ID"
          AND "A"."DISTRIBUTION_ACCOUNT_ID" = "CC"."CODE_COMBINATION_ID"
          AND "A"."ACCT_PERIOD_ID" = "PRD"."ACCT_PERIOD_ID"
          AND "A"."TRANSACTION_QUANTITY" < 0
          AND "A"."ORGANIZATION_ID" = "PRD"."ORGANIZATION_ID"
          AND "MTRL"."INVENTORY_ITEM_ID" = "A"."INVENTORY_ITEM_ID"
          AND "MTRL"."ORGANIZATION_ID" = "A"."ORGANIZATION_ID"
          AND "MTRL"."LINE_ID" = "A"."TRX_SOURCE_LINE_ID"
          AND "A"."TRANSACTION_SOURCE_ID" = "B"."HEADER_ID";