--Trade Fair Sales
SELECT V.SHOP_CODE,
       V.ORDER_NO,
       V.Status,
       V.SALES_DATE,
       V.PRODUCT_CODE,
       V.SALES_QUANTITY,
       V.SALES_PRICE,
       V.VAT,
       V.AMOUNT_RSP,
       V.DISCOUNT "DISCOUNT(%)"
  FROM IFSAPP.SBL_JR_SALES_INV_PKG_VIEW V
 WHERE V.DISTRICT_CODE = 40
   AND V.SHOP_CODE = '&SITE_CODE'
   AND V.SALES_DATE BETWEEN TO_DATE('&FROM_DATE', 'YYYY/MM/DD') AND
       TO_DATE('&TO_DATE', 'YYYY/MM/DD')
 ORDER BY 2, 5
