/* Formatted on 10/4/2020 5:17:11 PM (QP5 v5.287) */
CREATE OR REPLACE FUNCTION APPS.XX_GET_LCM_AMNT_FROM_PO_NO (
   P_TRANSACTION_ID   IN NUMBER)
   RETURN VARCHAR2
IS
   V_VENDOR_NAME   VARCHAR (240);

   CURSOR P_VENDOR_CURSOR
   IS
      SELECT MAX (LC_NUMBER)
        FROM RCV_TRANSACTIONS RCT, XX_LC_DETAILS XLD
       WHERE     RCT.PO_HEADER_ID = TO_NUMBER (XLD.PO_HEADER_ID)
             AND RCT.TRANSACTION_ID = P_TRANSACTION_ID;
BEGIN
   OPEN P_VENDOR_CURSOR;

   FETCH P_VENDOR_CURSOR INTO V_VENDOR_NAME;

   CLOSE P_VENDOR_CURSOR;

   RETURN (V_VENDOR_NAME);
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN NULL;
END;
/