/* Formatted on 5/26/2022 2:08:59 PM (QP5 v5.381) */
  SELECT CONTRACT, TO_CHAR (MAX (d.TO_DATE), 'DD-MON-YY') Last_dt
    FROM HPNRET_RSL d
   WHERE d.ROW_TYPE = 'RSL'
GROUP BY CONTRACT
  HAVING TRUNC (MAX (d.TO_DATE)) < SYSDATE - TO_NUMBER (&Days)