-- Test Correction of PKG Break
select COUNT(DISTINCT L.ORDER_NO)
  from IFSAPP.CUSTOMER_ORDER_LINE_TAB L
  LEFT JOIN IFSAPP.SBL_JR_SALES_DTL_PKG P
    ON L.ORDER_NO = P.ORDER_NO
   AND L.LINE_NO = P.LINE_NO
   AND L.REL_NO = P.REL_NO
 where L.CATALOG_TYPE = 'KOMP'
   AND P.SALES_DATE = TO_DATE('&SALES_DATE', 'MM/DD/YYYY');

--
select COUNT(T.ORDER_NO) from SBL_JR_SALES_DTL_PKG t
WHERE T.SALES_DATE = TO_DATE('&SALES_DATE', 'MM/DD/YYYY');
