/* Formatted on 8/22/2023 2:56:27 PM (QP5 v5.381) */
CREATE OR REPLACE FUNCTION IFSAPP.SBL_GET_BASE_PART_PRICE (
    P_PART_CODE         VARCHAR2,
    P_VALID_FROM_DATE   DATE,
    P_PRICE_LIST_NO     NUMBER)
    RETURN NUMBER
IS
    V_PART_PRICE   NUMBER (15, 5);
BEGIN
    -- CREATED BY : Sourav Paul
    -- CREATION DATE : 22-AUG-2023
    -- LAST UPDATE DATE : 22-AUG-2023
    -- PURPOSE : CALCULATING REALTIME ITEM PRICE BASED ON PRICE_LIST_NO AND VALID_DATE
    -- CHANGE IMPACT : CHNAGE MAY IMPACT MANY REPORT RELATED TO ITEM PRICE

    SELECT VALUE_WITHOUT_TAX
      INTO V_PART_PRICE
      FROM (SELECT ROW_NUMBER ()
                       OVER (PARTITION BY P.CATALOG_NO, P.PRICE_LIST_NO
                             ORDER BY P.VALID_FROM_DATE DESC)    ROW_NUM,
                   P.BASE_PRICE                                  VALUE_WITHOUT_TAX
              FROM IFSAPP.SALES_PRICE_LIST_PART_TAB P
             WHERE     1 = 1
                   AND P.CATALOG_NO = P_PART_CODE
                   AND P.VALID_FROM_DATE <= P_VALID_FROM_DATE
                   AND P.PRICE_LIST_NO = P_PRICE_LIST_NO)
     WHERE ROW_NUM < 2;

    RETURN (V_PART_PRICE);
EXCEPTION
    WHEN OTHERS
    THEN
        RETURN (NULL);
END;
/
