/* Formatted on 8/9/2020 9:51:36 AM (QP5 v5.287) */
DECLARE
   CUSTOMER_ID       AR_CUSTOMERS.CUSTOMER_ID%TYPE;
   CUSTOMER_NAME     AR_CUSTOMERS.CUSTOMER_NAME%TYPE;
   CUSTOMER_NUMBER   AR_CUSTOMERS.CUSTOMER_NUMBER%TYPE;

   CURSOR c_customers
   IS
      SELECT CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER
        FROM AR_CUSTOMERS
       WHERE 1 = 1 AND CUSTOMER_NUMBER = '1001';
BEGIN
   OPEN c_customers;

   LOOP
      FETCH c_customers INTO CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_NUMBER;

      EXIT WHEN c_customers%NOTFOUND;
      DBMS_OUTPUT.put_line (
         CUSTOMER_ID || ' ' || CUSTOMER_NAME || ' ' || CUSTOMER_NUMBER);
   END LOOP;

   CLOSE c_customers;
END;
/