--HP Receivable Exception List
SELECT H.YEAR,
       H.PERIOD,
       H.ACCT_NO,
       H.PRODUCT_CODE,
       H.CUSTOMER,
       ifsapp.customer_info_api.Get_Name(H.CUSTOMER) customer_name,
       TO_CHAR(H.SALES_DATE, 'MM/DD/YYYY') SALES_DATE,
       TO_CHAR(H.ACTUAL_SALES_DATE, 'MM/DD/YYYY') ACTUAL_SALES_DATE,
       H.AMOUNT_FINANCED,
       H.MONTHLY_PAY,
       H.LOC,
       H.TOTAL_UCC,
       H.ACT_OUT_BAL,
       H.ARR_MON,
       TO_CHAR(H.CASH_CONVERSION_ON_DATE, 'MM/DD/YYYY') CASH_CONVERSION_ON_DATE,
       H.EFFECTIVE_RATE,
       H.PRESENT_VALUE,
       H.EFFECTIVE_ECC,
       H.ACTUAL_UCC /*,
       H.SHOP_CODE,
       H.ORIGINAL_ACCT_NO,
       H.MORE_PRODUCTS,
       H.SALESMAN,
       H.SALES_CREATOR,
       H.HP_TYPE,
       TO_CHAR(H.REAL_SHIP_DATE, 'MM/DD/YYYY') REAL_SHIP_DATE,
       TO_CHAR(H.CLOSED_DATE, 'MM/DD/YYYY') CLOSED_DATE,
       H.STATE,
       H.LAST_VARIATION,
       H.BB_NO,
       IFSAPP.HPNRET_BB_MAIN_HEAD_API.Get_Description(H.BB_NO) BB_NAME,
       H.SCHEME,
       H.GROUP_SALE_NO,
       IFSAPP.CUSTOMER_INFO_API.Get_NIC_No(H.CUSTOMER) NIC,
       IFSAPP.CUSTOMER_INFO_ADDRESS_API.Get_Address1(H.CUSTOMER, 1) ADDRESS_1,
       IFSAPP.CUSTOMER_INFO_ADDRESS_API.Get_Address2(H.CUSTOMER, 1) ADDRESS_2,
       H.ORDER_TYPE,
       H.MC_CD,
       H.NORMAL_CASH_PRICE,
       H.HIRE_CASH_PRICE,
       H.HIRE_PRICE,
       H.LIST_PRICE,
       H.FIRST_PAY,
       H.DOWN_PAYMENT,
       H.SURAKSHA_AMOUNT,
       H.SANASUMA_AMOUNT,
       H.COMMODITY2,
       H.COLLECTION,
       H.DISCOUNT,
       H.ARR_AMT,
       H.OUTSTANDING_BAL,
       H.OUTSTANDING_MONTHS,
       H.OUTSTANDING_UCC,
       REPLACE(H.TEL_NO, ',', '_') TEL_NO,
       H.DEL_MON,
       to_char(H.ROWVERSION, 'MM/DD/YYYY') ROWVERSION,
       H.VAT,*/
/*COUNT(*)*/
  FROM HPNRET_FORM249_ARREARS_TAB H
 WHERE H.YEAR = '&YEAR_I'
   AND H.PERIOD = '&PERIOD'
   AND H.ACCT_NO in ('VAL-H3420',
                     'VAL-H3421',
                     'COX-H10037',
                     'CXN-H3596',
                     'CXN-H3597',
                     'SDM-H6827',
                     'DBA-H5660',
                     'DGN-H7035',
                     'COX-H9519',
                     'RGP-H6304',
                     'DFG-H1918',
                     'BCF-H1683',
                     'COX-H10208',
                     'CJT-H2981',
                     'CXN-H3186',
                     'CKR-H4192',
                     'CXN-H3534',
                     'DMA-H1858',
                     'CXN-H3573',
                     'CXN-H3575',
                     'CXN-H3614',
                     'CXN-H3615',
                     'CXN-H3616',
                     'CKR-H4077',
                     'KON-H4368',
                     'COX-H9903',
                     'COX-H9904',
                     'COX-H9905',
                     'COX-H9906',
                     'DSY-H5790',
                     'COX-H10125',
                     'COX-H10126',
                     'CXN-H4026',
                     'BCF-H2453',
                     'CXN-H4054',
                     'CXN-H4055',
                     'CXN-H4056',
                     'CXN-H4057',
                     'CXN-H4058',
                     'CXN-H4059',
                     'CXN-H4064',
                     'CXN-H4065',
                     'CXN-H4066',
                     'CXN-H4069',
                     'JES-H9525',
                     'JES-H9526',
                     'GRP-H4357',
                     'SCO-H58',
                     'ZIR-H3718',
                     'TKG-H4841',
                     'KUP-H1471')
 ORDER BY H.YEAR, H.PERIOD, H.SHOP_CODE, H.ORIGINAL_ACCT_NO, H.PRODUCT_CODE
