SELECT T2.CONTRACT
           SENDER,
       (SELECT ADDRESS1 || ' ' || ADDRESS2
          FROM IFSAPP.CUSTOMER_INFO_ADDRESS_TAB CA
         WHERE CA.CUSTOMER_ID = T2.CONTRACT)
           SENDER_ADDRESS,
       T2.CUSTOMER_NO
           RECIPIENT,
       (SELECT ADDRESS1 || ' ' || ADDRESS2
          FROM IFSAPP.CUSTOMER_INFO_ADDRESS_TAB CA
         WHERE CA.CUSTOMER_ID = T2.CUSTOMER_NO)
           RECIPIENT_ADDRESS,
       T2.DEMAND_ORDER_REF1
           PO_NUMBER,
       T4.ORDER_NO,
          T2.PART_NO
       || ' - '
       || T2.CATALOG_DESC
       || ' / '
       || IFSAPP.SERIAL_OEM_CONN_API.GET_OEM_NO (L.PART_NO, L.SERIAL_NO)
           PRODUCT_DESCRIPTION,
       NVL (
           IFSAPP.SBL_GET_BASE_PART_PRICE (L.PART_NO, T4.DATE_DELIVERED, '3'),
           0.00)
           VALUE_WITHOUT_TAX,
       T4.DELNOTE_NO,
       L.QTY_SHIPPED,
       T4.DATE_DELIVERED,
       (SELECT PIT.NAME
          FROM PERSON_INFO_TAB PIT
         WHERE PIT.PERSON_ID = L.SOURCE)
           FULL_NAME
  FROM IFSAPP.CUSTOMER_ORDER_DELIVERY_TAB    T4,
       IFSAPP.CUSTOMER_ORDER_LINE_TAB        T2,
       IFSAPP.CUSTOMER_ORDER_RES_SERIAL_LOV  L
 WHERE     T2.ORDER_NO = T4.ORDER_NO
       AND T2.LINE_NO = T4.LINE_NO
       AND T2.REL_NO = T4.REL_NO
       AND T2.LINE_ITEM_NO = T4.LINE_ITEM_NO
       AND T4.DELNOTE_NO = $P{DEBIT_NOTE_NO}
       AND T2.ORDER_NO = L.ORDER_NO
       AND T2.LINE_NO = L.LINE_NO
       AND T2.REL_NO = L.REL_NO
       AND T2.LINE_ITEM_NO = L.LINE_ITEM_NO