select distinct P.CONTRACT
    ,G.FULLY_PAID_VOUCHER_DATE
    ,substr(I.LEDGER_ITEM_ID,0,instr(I.LEDGER_ITEM_ID, '#')-1) DDNO
    ,(
      SELECT IFSAPP.HPNRET_BANK_API.Get_Name(BANK_ID) 
        FROM IFSAPP.CHECK_ENCASHMENT_TAB T
        WHERE T.CHECK_NO=I.LEDGER_ITEM_ID
            and t.SERIES_ID=I.LEDGER_ITEM_SERIES_ID
            and t.CUSTOMER_ID=i.identity
    ) BANK_NAME
    ,i.FULL_CURR_AMOUNT AMOUNT
    ,P.SHORT_NAME ACCOUNT_NO
    ,IFSAPP.CASH_ACCOUNT_API.Get_Account_Identity(P.COMPANY,p.SHORT_NAME) ACCOUNT_NO_DT
    ,IFSAPP.CASH_ACCOUNT_API.Get_Description(P.COMPANY,p.SHORT_NAME) ACCOUNT_NAME
    ,substr(I.LEDGER_ITEM_ID,instr(I.LEDGER_ITEM_ID, '#')+1,11) DD_DATE
    ,(
      SELECT t.LAST_DD_NO
      FROM IFSAPP.CHECK_ENCASHMENT_TAB T
      WHERE T.CHECK_NO=I.LEDGER_ITEM_ID
        and t.SERIES_ID=I.LEDGER_ITEM_SERIES_ID
        and t.CUSTOMER_ID=i.identity
    ) LAST_DDNO
    ,decode(
      (
      SELECT t.LAST_DD_NO 
      FROM ifsapp.CHECK_ENCASHMENT_TAB T
      WHERE T.CHECK_NO=I.LEDGER_ITEM_ID
        and t.SERIES_ID=I.LEDGER_ITEM_SERIES_ID
        and t.CUSTOMER_ID=i.identity
      )
      , NULL, substr(I.LEDGER_ITEM_ID,0,instr(I.LEDGER_ITEM_ID, '#')-1),
      (
      SELECT t.LAST_DD_NO 
      FROM ifsapp.CHECK_ENCASHMENT_TAB T
      WHERE T.CHECK_NO=I.LEDGER_ITEM_ID
        and t.SERIES_ID=I.LEDGER_ITEM_SERIES_ID
        and t.CUSTOMER_ID=i.identity
      )
    ) DDNO_FINAL
from IFSAPP.CHECK_CASH_PROPOSAL P ,
    IFSAPP.CHECK_CASH_PROPOSAL_ITEM I,
    IFSAPP.CHECK_LEDGER_ITEM G
where p.PROPOSAL_ID=i.PROPOSAL_ID
    and I.LEDGER_ITEM_SERIES_ID=G.LEDGER_ITEM_SERIES_ID
    and I.identity=G.identity
    and I.LEDGER_ITEM_ID=G.LEDGER_ITEM_ID
    and P.SHORT_NAME like '&SHORT_NAME'
    and trunc(G.FULLY_PAID_VOUCHER_DATE)  BETWEEN TO_DATE('&From_Date','YYYY/MM/DD') AND TO_DATE('&To_Date','YYYY/MM/DD')
    and P.CONTRACT like '&SITE'
    AND (
      SELECT upper(IFSAPP.HPNRET_BANK_API.Get_Name(BANK_ID))
      FROM IFSAPP.CHECK_ENCASHMENT_TAB T
      WHERE T.CHECK_NO=I.LEDGER_ITEM_ID
        and t.SERIES_ID=I.LEDGER_ITEM_SERIES_ID
        and t.CUSTOMER_ID=i.identity
    ) LIKE upper('%&BANK_NAME%')
