/* Formatted on 3/23/2022 10:10:01 AM (QP5 v5.381) */
SELECT T.CUSTOMER_ID     CUST_ID,
       B.NAME            CUST_NAME,
       A.ADDRESS1        ADDRESS_LINE_1,
       A.ADDRESS2        ADDRESS_LINE_2,
       T.VALUE           PHONE
  FROM IFSAPP.CUSTOMER_INFO_COMM_METHOD  T,
       IFSAPP.CUSTOMER_INFO_ADDRESS      A,
       IFSAPP.CUSTOMER_INFO              B,
       IFSAPP.IDENTITY_PAY_INFO             IPI
 WHERE     T.CUSTOMER_ID = A.CUSTOMER_ID
       AND T.CUSTOMER_ID = B.CUSTOMER_ID
       AND B.CUSTOMER_ID = IPI.IDENTITY(+)
       AND IPI.PARTY_TYPE_DB = 'CUSTOMER';