/* Formatted on 5/16/2022 2:49:05 PM (QP5 v5.381) */
  SELECT S.CONTRACT,
         S.USERID,
         (SELECT IFSAPP.sbl_pass (S.USERID) FROM DUAL)     PASSWORD
    FROM IFSAPP.USER_ALLOWED_SITE S
   WHERE S.USER_SITE_TYPE_DB = 'DEFAULT SITE'
ORDER BY S.CONTRACT ASC