select
U.IDENTITY,
U.PARTY_NAME,
U.LEDGER_ITEM_SERIES_ID,
U.REST_AMOUNT,
U.DUE_DATE,
U.OBJSTATE
from
IFSAPP.LEDGER_ITEM3_EMU U
where U.IDENTITY like 'W00%'
or U.IDENTITY like 'S00%'
or U.IDENTITY like 'WIT00%'
or U.IDENTITY like 'IT00%'