/* Formatted on 8/26/2021 10:42:07 AM (QP5 v5.287) */
EXEC AD_ZD_MVIEW.UPGRADE('APPS','XXDBL_AR_LIAB_EXP_BILL_MV');

GRANT SELECT ON APPS.XXDBL_AR_LIAB_EXP_BILL_MV TO APPSRO;

GRANT SELECT ON APPS.XXDBL_AR_LIAB_EXP_BILL_MV# TO APPSRO;