/* Formatted on 1/22/2023 3:30:24 PM (QP5 v5.381) */
SELECT * FROM SBL_SAP_INTG_CUSTOMER;

SELECT * FROM SBL_SAP_INTG_VENDOR;

SELECT * FROM SBL_SAP_INTG_SALES_INV;

SELECT * FROM SBL_SAP_INTG_CO_PAY_LINE;

SELECT * FROM SBL_SAP_INTG_CO_PAY_HEAD_CL;

SELECT * FROM SBL_SAP_INTG_CO_PAY_LINE_CL;

SELECT * FROM SBL_SAP_INTG_HP_DP_HEAD;

SELECT * FROM SBL_SAP_INTG_HP_DP_LINE;

SELECT * FROM SBL_SAP_INTG_HP_DP_HEAD_CL;

SELECT * FROM SBL_SAP_INTG_HP_DP_LINE_CL;

SELECT * FROM SBL_SAP_INTG_PO_HEAD;

SELECT * FROM SBL_SAP_INTG_PO_LINE;

SELECT * FROM SBL_SAP_INTG_PKG_ITEM;

SELECT * FROM SBL_SAP_INTG_SHIP_HEAD;

SELECT * FROM SBL_SAP_INTG_SHIP_LINE;

SELECT * FROM SBL_SAP_INTG_SHIP_CHARGE;

SELECT * FROM SBL_SAP_INTG_GOODS_RECEIPT;

SELECT * FROM SBL_SAP_INTG_CCP_HEAD;

SELECT * FROM SBL_SAP_INTG_CCP_LINE;