/* Formatted on 1/1/2023 10:31:08 AM (QP5 v5.381) */
SELECT * FROM SBL_SAP_INTG_CUSTOMER;

SELECT * FROM SBL_SAP_INTG_VENDOR;

SELECT * FROM SBL_SAP_INTG_SALES_INV;

SELECT * FROM SBL_SAP_INTG_CO_PAY_LINE;

SELECT * FROM SBL_SAP_INTG_CO_PAY_HEAD_CL;

SELECT * FROM SBL_SAP_INTG_CO_PAY_LINE_CL;