/* Formatted on 1/23/2023 12:29:36 PM (QP5 v5.381) */
SELECT * FROM IFSAPP.PURCHASE_RECEIPT_SCRAP_TAB;


SELECT * FROM IFSAPP.RETURN_MATERIAL_SCRAP_TAB;


SELECT * FROM IFSAPP.SCRAP_CUSTOMER_ORDER_RETURN;

SELECT ORDER_NO
           ORDER_NO,
       LINE_NO
           LINE_NO,
       REL_NO
           REL_NO,
       LINE_ITEM_NO
           LINE_ITEM_NO,
       SERIAL_NO
           SERIAL_NO,
       ROWID
           OBJID,
       LTRIM (LPAD (TO_CHAR (ROWVERSION, 'YYYYMMDDHH24MISS'), 2000))
           OBJVERSION,
       CORT.*
  FROM CUSTOMER_ORDER_RESERVATION_TAB CORT
 WHERE 1 = 1 AND QTY_SHIPPED > 0;

SELECT * FROM IFSAPP.RETURN_MATERIAL_SCRAP_TAB;

SELECT * FROM IFSAPP.SCRAPPING_CAUSE_TAB;


SELECT *
  FROM IFSAPP.SBL_SAP_INTG_SALES_INV
 WHERE 1 = 1 AND SITE_CODE = 'SISM' AND DOCUMENT_NUMBER = 'SIS-R1043';