/* Formatted on 11/22/2020 5:18:56 PM (QP5 v5.287) */
SELECT get_dept_name_from_user_name ('103908', NULL) dept_name FROM DUAL;


SELECT APPS.XX_COM_PKG.GET_DEPT_FROM_USER_NAME_ID (NULL, 2734) DEPT_NAME FROM DUAL;

SELECT XX_COM_PKG.GET_DEPT_FROM_USER_NAME_ID ('PROD_SETUP', NULL) DEPT_NAME FROM DUAL;