--***** Purchase Order Check
select L.*
  from IFSAPP.PURCHASE_ORDER_LINE_TAB L
 INNER JOIN IFSAPP.PURCHASE_ORDER_TAB P
    ON L.ORDER_NO = P.ORDER_NO
 WHERE P.VENDOR_NO = 'DMMB'
   AND P.CONTRACT = 'IBRD'
   AND L.PART_NO LIKE '%12L78%' -- 4521 BD11R00269 4871 BD09R00136
