/* Formatted on 7/28/2021 12:33:46 PM (QP5 v5.287) */
SELECT *
  FROM APPS.XXDBLCL_SALES_ORDER_DTL_MV#
 --WHERE ROWNUM < 10
 ;

SELECT *
  FROM APPS.XXDBLCL_SALES_ORDER_DTL_MV
 WHERE 1 = 1
--AND TO_CHAR (TRANSACTION_DATE, 'DD-MON-YY') = '01-FEB-21'
--AND TO_CHAR (TRANSACTION_DATE, 'MON-YY') = 'FEB-21'
--AND ASSET IS NOT NULL
--AND ORGANIZATION_ID = 195
;


SELECT * FROM APPS.XX_GL_DETAILS_STATEMENT_V;


EXECUTE APPS.xxdbl_mview_dtld_pkg.run_mview_dataload_proc;

--apps.xxdbl_mview_dtld_pkg.run_mview_dataload_conc;

--------------------------------------------------------------------------------
--EXECUTE APPS.xxdbl_mview_dtld_pkg.run_scheduler_job_proc;

--apps.xxdbl_mview_dtld_pkg.run_scheduler_job_conc;

--------------------------------------------------------------------------------

CREATE OR REPLACE FORCE VIEW APPS.XX_GL_DETAILS_STATEMENT_V
(
   SL,
   APPLICATION_ID,
   JE_SOURCE,
   JE_CATEGORY,
   UNIT_NAME,
   COMPANY,
   LOCATION,
   PRODUCT_LINE,
   COST_CENTER,
   ACCOUNT,
   SUB_ACCOUNT,
   INTER_COMPANY,
   EXPENSE_CATEGORY,
   FUTURE,
   ACCTDESC,
   SUBACCDESC,
   VOUCHER_NUMBER_2,
   VOUCHER_NUMBER,
   GL_VOUCHER_NUMBER,
   GL_JE_LINE_NUM,
   VOUCHER_DATE,
   DESCRIPTION,
   CURRENCY_CODE,
   CONVERSION_RATE,
   CREATED_BY,
   ENTERED_DEBITS,
   ENTERED_CREDITS,
   DEBITS,
   CREDITS,
   REVERSAL_TYPE,
   REVERSE_PERIOD,
   CHEQUE_NUMBER,
   CHEQUE_DATE,
   PARTY_CODE,
   PARTY_NAME,
   TRANSACTION_TYPE,
   CHART_OF_ACCOUNTS_ID,
   LEDGER_ID,
   DFF_CONTEXT,
   ATTRIBUTE1,
   ATTRIBUTE2,
   ATTRIBUTE3,
   ATTRIBUTE4,
   ATTRIBUTE5
)
   BEQUEATH DEFINER
AS
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          --AND NVL (NVL (GJL.ACCOUNTED_DR, GJL.ACCOUNTED_CR), 0) <> 0 #Bug - Journal Line Debit and Credit both column has value
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          --    AND GJH.JE_SOURCE NOT IN ('Payables',
          -- --                   'Receivables',
          --            'Cash Management',
          --             'Assets',
          --       'Inventory',
          --      'Cost Management')
          --AND NVL (GJH.JE_FROM_SLA_FLAG, 'N') <> 'Y'
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJH.JE_HEADER_ID = 489614
   UNION ALL
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          --AND NVL (NVL (GJL.ACCOUNTED_DR, GJL.ACCOUNTED_CR), 0) <> 0 #Bug - Journal Line Debit and Credit both column has value
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          --    AND GJH.JE_SOURCE NOT IN ('Payables',
          -- --                   'Receivables',
          --            'Cash Management',
          --             'Assets',
          --       'Inventory',
          --      'Cost Management')
          AND NVL (GJH.JE_FROM_SLA_FLAG, 'N') <> 'Y'
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
   UNION ALL
   --OPM Batch Close
   SELECT 1 SL,
          101 APPLICATION_ID,
          SRC.USER_JE_SOURCE_NAME JE_SOURCE,
          CAT.NAME JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJH.DEFAULT_EFFECTIVE_DATE VOUCHER_DATE,
          GJL.DESCRIPTION,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (GJL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (GJL.ENTERED_CR, 0) ENTERED_CREDITS,
          NVL (GJL.ACCOUNTED_DR, 0) DEBITS,
          NVL (GJL.ACCOUNTED_CR, 0) CREDITS,
          GJH.ACCRUAL_REV_STATUS REVERSAL_TYPE,
          GJH.ACCRUAL_REV_PERIOD_NAME REVERSE_PERIOD,
          GJL.ATTRIBUTE2 CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          'MANUAL_JV' TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          GJL.CONTEXT DFF_CONTEXT,
          GJL.ATTRIBUTE1,
          GJL.ATTRIBUTE2,
          GJL.ATTRIBUTE3,
          GJL.ATTRIBUTE4,
          GJL.ATTRIBUTE5
     FROM GL_JE_HEADERS GJH,
          APPS.GL_JE_LINES GJL,
          FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_JE_SOURCES_TL SRC,
          APPS.GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJH.JE_CATEGORY = CAT.CODE     --   AND CAT.APPLICATION_ID = 101
          AND GJH.JE_SOURCE = SRC.JE_SOURCE_NAME
          --AND NVL (NVL (GJL.ACCOUNTED_DR, GJL.ACCOUNTED_CR), 0) <> 0 #Bug - Journal Line Debit and Credit both column has value
          AND (   NVL (GJL.ACCOUNTED_DR, 0) <> 0
               OR NVL (GJL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          --    AND GJH.JE_SOURCE NOT IN ('Payables',
          -- --                   'Receivables',
          --            'Cash Management',
          --             'Assets',
          --       'Inventory',
          --      'Cost Management')
          --     AND NVL (GJH.JE_FROM_SLA_FLAG, 'N') <> 'Y'
          AND GJL.STATUS = 'P'
          AND GJH.ACTUAL_FLAG = 'A'
          AND CAT.NAME = 'OPM Batch Close'
   UNION ALL
   -- Receivable Transaction Invoice
   SELECT 2 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.BILL_TO_CUSTOMER_ID
          AND CT.CUSTOMER_TRX_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          --          AND XTE.ENTITY_CODE IN ('TRANSACTIONS', 'ADJUSTMENTS') --#Bug Adjustment Transactions are Missing and Added a new Union
          AND XTE.ENTITY_CODE IN ('TRANSACTIONS')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Bill Receivable
   SELECT 3 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          CT.TRX_NUMBER VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.DRAWEE_ID
          AND CT.CUSTOMER_TRX_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          --          AND XTE.ENTITY_CODE IN ('TRANSACTIONS', 'ADJUSTMENTS') --#Bug Adjustment Transactions are Missing and Added a new Union
          AND XTE.ENTITY_CODE IN ('BILLS_RECEIVABLE')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Only for Adjustoments
   SELECT 4 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CT.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Trx No-' || CT.TRX_NUMBER)
             PARTICULARS,
          CT.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          CT.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (ADJ.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CT.ATTRIBUTE1,
          CT.ATTRIBUTE2,
          CT.ATTRIBUTE3,
          CT.ATTRIBUTE4,
          CT.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          RA_CUSTOMER_TRX_ALL CT,
          AR_ADJUSTMENTS_ALL ADJ,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID = CT.BILL_TO_CUSTOMER_ID
          AND CT.CUSTOMER_TRX_ID = ADJ.CUSTOMER_TRX_ID
          AND ADJ.ADJUSTMENT_ID(+) = XTE.SOURCE_ID_INT_1
          AND CUST.ORG_ID = XTE.SECURITY_ID_INT_1
          AND XTE.ENTITY_CODE IN ('ADJUSTMENTS')
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE = 'BILL_TO'
          AND CUST.PRIMARY_FLAG = 'Y'
   UNION ALL
   -- Receipt
   SELECT 5 SL,
          222 APPLICATION_ID,
          'AR' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (CR.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAH.ACCOUNTING_DATE VOUCHER_DATE,
          ('Cust-' || CUST.CUSTOMER_NUMBER || ' Rcv No-' || CR.RECEIPT_NUMBER)
             PARTICULARS,
          CR.CURRENCY_CODE,
          CR.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CR.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          CUST.CUSTOMER_NUMBER PARTY_CODE,
          CUST.CUSTOMER_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CR.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CR.ATTRIBUTE1,
          CR.ATTRIBUTE2,
          CR.ATTRIBUTE3,
          CR.ATTRIBUTE4,
          CR.ATTRIBUTE5
     FROM XX_AR_CUSTOMER_SITE_V CUST,
          AR_CASH_RECEIPTS_ALL CR,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     CUST.CUSTOMER_ID(+) = CR.PAY_FROM_CUSTOMER
          AND CUST.ORG_ID(+) = CR.ORG_ID
          AND CR.CASH_RECEIPT_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.ENTITY_CODE = 'RECEIPTS'
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 222
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND NVL (NVL (XAL.ACCOUNTED_DR, XAL.ACCOUNTED_CR), 0) <> 0
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND CUST.SITE_USE_CODE(+) = 'BILL_TO'
          AND CUST.PRIMARY_FLAG(+) = 'Y'
   UNION ALL
   -- Payables Invoice
   SELECT 6 SL,
          200 APPLICATION_ID,
          'AP' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (API.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          XAL.DESCRIPTION PARTICULARS,
          API.INVOICE_CURRENCY_CODE CURRENCY_CODE,
          API.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (API.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          API.INVOICE_NUM CHEQUE_NUMBER,
          --NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          API.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          API.ATTRIBUTE1,
          API.ATTRIBUTE2,
          API.ATTRIBUTE3,
          API.ATTRIBUTE4,
          API.ATTRIBUTE5
     FROM AP_SUPPLIERS APS,
          AP_INVOICES_ALL API,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     NVL (APS.VENDOR_ID(+), -222) = API.VENDOR_ID
          AND API.INVOICE_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.ENTITY_CODE = 'AP_INVOICES'
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 200
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   -- Payables Invoice Payment
   SELECT 7 SL,
          200 APPLICATION_ID,
          'AP' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_HR_OPERATING_UNIT (APC.ORG_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          XAH.DOC_SEQUENCE_VALUE VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          APC.DESCRIPTION PARTICULARS,
          APC.CURRENCY_CODE,
          APC.EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (APC.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          --PHP_AP_PKG.FIND_CHECK_NUMBER (APC.CHECK_NUMBER, APC.CHECK_ID)
          TO_CHAR (APC.CHECK_NUMBER) CHEQUE_NUMBER,
          --NULL CHEQUE_NUMBER,
          TRUNC (APC.CHECK_DATE) CHEQUE_DATE,
          --XX_AP_PKG.GET_VENDOR_NUMBER (APC.VENDOR_ID) PARTY_CODE,
          --          DECODE (
          --             XAH.EVENT_TYPE_CODE,
          --             'PAYMENT CREATED HARUN', XX_AP_PKG.GET_BANK_NAME_FROM_ACCT_USE_ID (
          --                                       APC.CE_BANK_ACCT_USE_ID),
          --             APC.VENDOR_NAME)
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          APC.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          APC.ATTRIBUTE1,
          APC.ATTRIBUTE2,
          APC.ATTRIBUTE3,
          APC.ATTRIBUTE4,
          APC.ATTRIBUTE5
     FROM AP_CHECKS_ALL APC,
          AP_SUPPLIERS APS,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     APC.VENDOR_ID = NVL (APS.VENDOR_ID(+), -222)
          AND APC.CHECK_ID = XTE.SOURCE_ID_INT_1
          AND XTE.ENTITY_CODE = 'AP_PAYMENTS'
          AND XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XAH.AE_HEADER_ID = XAL.AE_HEADER_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 200
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   -- Bank Transfer
   SELECT 8 SL,
          260 APPLICATION_ID,
          'CM' JE_SOURCE,
          GJH.JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          CPT.TRXN_REFERENCE_NUMBER VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GLL.JE_LINE_NUM GL_JE_LINE_NUM,
          XEL.ACCOUNTING_DATE VOUCHER_DATE,
          --PHP_CE_PKG.get_transaction_history (CPT.TRXN_REFERENCE_NUMBER)
          NULL PARTICULARS,
          CFLOW.CASHFLOW_CURRENCY_CODE CURRENCY_CODE,
          CFLOW.CASHFLOW_EXCHANGE_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (CFLOW.CREATED_BY)
             CREATED_BY,
          NVL (XEL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XEL.ENTERED_CR, 0) ENTERED_CREDITS,
          XEL.ACCOUNTED_DR,
          XEL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          CPT.ATTRIBUTE1 CHEQUE_NUMBER,
          --TRUNC (TO_DATE (CPT.ATTRIBUTE2, 'YYYY/MM/DD HH24:MI:SS'))
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          CPT.ATTRIBUTE_CATEGORY DFF_CONTEXT,
          CPT.ATTRIBUTE1,
          CPT.ATTRIBUTE2,
          CPT.ATTRIBUTE3,
          CPT.ATTRIBUTE4,
          CPT.ATTRIBUTE5
     FROM GL_JE_LINES GLL,
          GL_JE_HEADERS GJH,
          GL_IMPORT_REFERENCES GIR,
          XLA_AE_LINES XEL,
          XLA_AE_HEADERS XEH,
          CE_PAYMENT_TRANSACTIONS CPT,
          CE_CASHFLOWS CFLOW,
          XLA.XLA_TRANSACTION_ENTITIES XTE,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     XTE.APPLICATION_ID = 260
          AND XEL.APPLICATION_ID = XEH.APPLICATION_ID
          AND XTE.APPLICATION_ID = XEH.APPLICATION_ID
          AND XEL.AE_HEADER_ID = XEH.AE_HEADER_ID
          AND XTE.ENTITY_CODE = 'CE_CASHFLOWS'
          AND XTE.SOURCE_ID_INT_1 = CFLOW.CASHFLOW_ID
          AND CPT.TRXN_REFERENCE_NUMBER = CFLOW.TRXN_REFERENCE_NUMBER
          AND XTE.ENTITY_ID = XEH.ENTITY_ID
          AND XEL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GIR.JE_HEADER_ID = GLL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GLL.JE_LINE_NUM
          AND (   NVL (XEL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XEL.ACCOUNTED_CR, 0) <> 0)
          AND GLL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GLL.STATUS = 'P'
   UNION ALL
   SELECT 9 SL,
          140 APPLICATION_ID,
          'FA' JE_SOURCE,
          GJH.JE_CATEGORY,
          NULL UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          GJL.EFFECTIVE_DATE VOUCHER_DATE,
          XAL.DESCRIPTION PARTICULARS,
          GJH.CURRENCY_CODE,
          GJH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GJH.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL,
          NULL,
          --APS.SEGMENT1 PARTY_CODE,
          --APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          NULL,
          NULL,
          NULL,
          NULL,
          NULL,
          NULL
     FROM XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX
    WHERE     XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID = 140
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          --AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
   UNION ALL
   SELECT 10 SL,
          XAL.APPLICATION_ID,
          'DIS_INV' JE_SOURCE,
          GJH.JE_CATEGORY,
          APPS.XX_COM_PKG.GET_ORGANIZATION_NAME (ORGANIZATION_ID) UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          NVL (
             TO_NUMBER (APPS.XX_GET_RCV_NUMBER_FROM_TRX_ID (SOURCE_ID_INT_1)),
             GJH.DOC_SEQUENCE_VALUE)
             VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          (SELECT MSI.DESCRIPTION
             FROM APPS.MTL_SYSTEM_ITEMS_B MSI
            WHERE     MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
                  AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID)
             PARTICULARS,
          --    XAL.DESCRIPTION PARTICULARS,
          MMT.CURRENCY_CODE,
          MMT.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (MMT.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          APPS.XX_GET_LC_NUMBER_FROM_TRX_ID (SOURCE_ID_INT_1) CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APPS.XX_GET_VENDOR_CODE_FROM_TRX_ID (SOURCE_ID_INT_1) PARTY_CODE,
          APPS.XX_GET_VENDOR_NAME_FROM_TRX_ID (SOURCE_ID_INT_1) PARTY_NAME,
          --APS.SEGMENT1 PARTY_CODE,
          --APS.VENDOR_NAME PARTY_NAME,
          XTE.ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          MMT.ATTRIBUTE_CATEGORY,
          MMT.ATTRIBUTE1,
          MMT.ATTRIBUTE2,
          MMT.ATTRIBUTE3,
          MMT.ATTRIBUTE4,
          MMT.ATTRIBUTE5
     FROM XLA.XLA_TRANSACTION_ENTITIES XTE,
          XLA_AE_HEADERS XAH,
          XLA_AE_LINES XAL,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX,
          MTL_MATERIAL_TRANSACTIONS MMT
    WHERE     XTE.ENTITY_ID = XAH.ENTITY_ID
          AND XTE.APPLICATION_ID = XAH.APPLICATION_ID
          AND XAH.APPLICATION_ID NOT IN (140,
                                         200,
                                         222,
                                         260,
                                         555)
          AND XAH.APPLICATION_ID = XAL.APPLICATION_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GJH.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND XTE.SOURCE_ID_INT_1 = MMT.TRANSACTION_ID(+)
   --AND MMT.CURRENCY_CODE != 'BDT'
   UNION ALL
   /*SELECT 11 SL,                                              --ADDED BY Majid
          XAL.APPLICATION_ID,
          'OPM_INV_RCV' JE_SOURCE,
          --GEH.ENTITY_CODE,
          XAH.JE_CATEGORY_NAME JE_CATEGORY,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                        (SELECT FLEX_VALUE
                           FROM FND_FLEX_VALUES_VL B
                          WHERE FLEX_VALUE_SET_ID = 1017040
                                AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          GEH.TRANSACTION_ID VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          NULL PARTICULARS,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          NULL DFF_CONTEXT,
          NULL ATTRIBUTE1,
          NULL ATTRIBUTE2,
          NULL ATTRIBUTE3,
          NULL ATTRIBUTE4,
          NULL ATTRIBUTE5
     FROM APPS.XLA_AE_LINES XAL,
          APPS.XLA_AE_HEADERS XAH,
          APPS.GL_IMPORT_REFERENCES GIR,
          APPS.GL_JE_LINES GJL,
          APPS.GL_JE_HEADERS GJH,
          APPS.FND_DOC_SEQUENCE_CATEGORIES CAT,
          APPS.GL_CODE_COMBINATIONS CC,
          APPS.FND_FLEX_VALUES_VL FLEX,
          APPS.MTL_SYSTEM_ITEMS_B MST,
          APPS.ORG_ORGANIZATION_DEFINITIONS ORG,
          APPS.MTL_ITEM_CATEGORIES MIC,
          APPS.MTL_CATEGORIES_B MCB,
          APPS.GMF_XLA_EXTRACT_HEADERS GEH,
          APPS.GMF_XLA_EXTRACT_LINES GEL,
          APPS.XLA_DISTRIBUTION_LINKS XDL,
          APPS.RCV_TRANSACTIONS RT,
          APPS.RCV_SHIPMENT_HEADERS RSH,
          APPS.RCV_SHIPMENT_LINES RSL,
          APPS.AP_SUPPLIERS APS
    WHERE     XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GEH.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND GEH.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND GEH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
          AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND MCB.STRUCTURE_ID = 101
          AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GEH.HEADER_ID = GEL.HEADER_ID
          AND GEH.EVENT_ID = GEL.EVENT_ID
          AND XDL.SOURCE_DISTRIBUTION_TYPE = GEH.ENTITY_CODE
          AND XDL.EVENT_ID = GEH.EVENT_ID
          AND XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = GEL.LINE_ID
          AND XDL.APPLICATION_ID = 555
          AND CATEGORY_SET_ID = 1
          AND GEH.SOURCE_LINE_ID(+) = RT.TRANSACTION_ID
          AND RSH.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
          AND RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
          AND RSL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID
          AND APS.VENDOR_ID = RSH.VENDOR_ID
          AND GEH.ENTITY_CODE = 'PURCHASING'*/
   --      SELECT 11 SL,                                              --ADDED BY Majid
   --             XAL.APPLICATION_ID,
   --             'OPM_INV_RCV' JE_SOURCE,
   --             CAT.NAME JE_CATEGORY,
   --             --gxeh.EVENT_CLASS_CODE,
   --             CC.SEGMENT1 COMPANY,
   --             CC.SEGMENT2 LOCATION,
   --             CC.SEGMENT3 PRODUCT_LINE,
   --             CC.SEGMENT4 COST_CENTER,
   --             CC.SEGMENT5 ACCOUNT,
   --             CC.SEGMENT6 SUB_ACCOUNT,
   --             CC.SEGMENT7 INTER_COMPANY,
   --             CC.SEGMENT8 EXPENSE_CATEGORY,
   --             CC.SEGMENT9 FUTURE,
   --             FLEX.DESCRIPTION ACCTDESC,
   --             (SELECT DESCRIPTION
   --                FROM FND_FLEX_VALUES_VL A
   --               WHERE A.FLEX_VALUE_SET_ID = 1017041
   --                     AND A.FLEX_VALUE = CC.SEGMENT6
   --                     AND PARENT_FLEX_VALUE_LOW =
   --                           (SELECT FLEX_VALUE
   --                              FROM FND_FLEX_VALUES_VL B
   --                             WHERE FLEX_VALUE_SET_ID = 1017040
   --                                   AND B.FLEX_VALUE = CC.SEGMENT5))
   --                SUBACCDESC,
   --             TO_CHAR (NULL) VOUCHER_NUMBER_2,
   --             GXEH.SOURCE_LINE_ID VOUCHER_NUMBER,
   --             GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
   --             XAL.AE_LINE_NUM GL_JE_LINE_NUM,
   --             XAL.ACCOUNTING_DATE VOUCHER_DATE,
   --             NULL PARTICULARS,
   --             NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
   --             NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
   --             XAL.ACCOUNTED_DR,
   --             XAL.ACCOUNTED_CR,
   --             NULL CHEQUE_NUMBER,
   --             TRUNC (SYSDATE) CHEQUE_DATE,
   --             APS.SEGMENT1 PARTY_CODE,
   --             APS.VENDOR_NAME PARTY_NAME,
   --             ENTITY_CODE TRANSACTION_TYPE,
   --             CC.CHART_OF_ACCOUNTS_ID,
   --             XAH.LEDGER_ID,
   --             NULL DFF_CONTEXT,
   --             NULL ATTRIBUTE1,
   --             NULL ATTRIBUTE2,
   --             NULL ATTRIBUTE3,
   --             NULL ATTRIBUTE4,
   --             NULL ATTRIBUTE5
   --        FROM AP_SUPPLIERS APS,
   --             RCV_SHIPMENT_HEADERS RCVH,
   --             RCV_TRANSACTIONS RCVT,
   --             PO_HEADERS_ALL POH,
   --             PO_LINES_ALL PLL,
   --             GMF_XLA_EXTRACT_HEADERS GXEH,
   --             XLA_AE_LINES XAL,
   --             XLA_AE_HEADERS XAH,
   --             FND_DOC_SEQUENCE_CATEGORIES CAT,
   --             GL_CODE_COMBINATIONS CC,
   --             FND_FLEX_VALUES_VL FLEX,
   --             MTL_SYSTEM_ITEMS_B_KFV MST,
   --             ORG_ORGANIZATION_DEFINITIONS ORG,
   --             MTL_ITEM_CATEGORIES MIC,
   --             MTL_CATEGORIES_B MCB,
   --             GL_IMPORT_REFERENCES GIR,
   --             GL_JE_HEADERS GJH,
   --             GL_JE_LINES GJL,
   --             GL_LEDGERS GL
   --       WHERE     APS.VENDOR_ID(+) = RCVH.VENDOR_ID
   --             AND RCVH.SHIPMENT_HEADER_ID(+) = RCVT.SHIPMENT_HEADER_ID
   --             AND GXEH.SOURCE_LINE_ID = RCVT.TRANSACTION_ID(+)
   --             AND GXEH.ORGANIZATION_ID = RCVT.ORGANIZATION_ID(+)
   --             AND POH.PO_HEADER_ID = PLL.PO_HEADER_ID
   --             AND RCVT.PO_HEADER_ID = PLL.PO_HEADER_ID
   --             AND RCVT.PO_LINE_ID = PLL.PO_LINE_ID
   --             AND XAH.EVENT_ID = GXEH.EVENT_ID
   --             AND XAH.LEDGER_ID = GXEH.LEDGER_ID
   --             AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
   --             AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
   --             AND XAH.JE_CATEGORY_NAME = CAT.CODE
   --             AND MIC.CATEGORY_SET_ID = 1
   --             AND CAT.APPLICATION_ID = 101
   --             AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
   --             AND GXEH.ORGANIZATION_ID = MST.ORGANIZATION_ID
   --             AND GXEH.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
   --             AND GXEH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
   --             AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
   --             AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
   --             AND MCB.STRUCTURE_ID = 101
   --             AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
   --             AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0
   --                  OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
   --             AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
   --             AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
   --             AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
   --             AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
   --             AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
   --             AND GJH.LEDGER_ID = GL.LEDGER_ID
   --             AND LEDGER_CATEGORY_CODE = 'PRIMARY'
   --             AND GJH.ACTUAL_FLAG = 'A'
   --             AND GJL.STATUS = 'P'
   --             AND CAT.NAME IN ('OPM Inv Receipts', 'Receiving')
   --   UNION ALL
   SELECT 12 SL,                                            ----ADDED BY Majid
          XAH.APPLICATION_ID,
          'OPM_INV' JE_SOURCE,
          --     EVENT_CLASS_CODE,
          --GXEH.ENTITY_CODE,
          XAH.JE_CATEGORY_NAME JE_CATEGORY,
          ORG.ORGANIZATION_NAME UNIT_NAME,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE     A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                         (SELECT FLEX_VALUE
                            FROM FND_FLEX_VALUES_VL B
                           WHERE     FLEX_VALUE_SET_ID = 1017040
                                 AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GXEH.TRANSACTION_ID VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          XAL.AE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          NULL PARTICULARS,
          GXEH.CURRENCY_CODE,
          GXEH.CURRENCY_CONVERSION_RATE CONVERSION_RATE,
          APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (GXEH.CREATED_BY)
             CREATED_BY,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          XAL.ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL REVERSAL_TYPE,
          NULL REVERSE_PERIOD,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          NULL PARTY_CODE,
          NULL PARTY_NAME,
          ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          XAH.LEDGER_ID,
          NULL DFF_CONTEXT,
          NULL ATTRIBUTE1,
          NULL ATTRIBUTE2,
          NULL ATTRIBUTE3,
          NULL ATTRIBUTE4,
          NULL ATTRIBUTE5
     FROM GMF_XLA_EXTRACT_HEADERS GXEH,
          XLA_AE_LINES XAL,
          XLA_AE_HEADERS XAH,
          --  FND_DOC_SEQUENCE_CATEGORIES CAT,
          GL_CODE_COMBINATIONS CC,
          FND_FLEX_VALUES_VL FLEX,
          MTL_SYSTEM_ITEMS_B_KFV MST,
          ORG_ORGANIZATION_DEFINITIONS ORG,
          MTL_ITEM_CATEGORIES_V MIC,
          GL_IMPORT_REFERENCES GIR,
          GL_JE_HEADERS GJH,
          GL_JE_LINES GJL
    WHERE     XAH.EVENT_ID = GXEH.EVENT_ID
          AND XAH.LEDGER_ID = GXEH.LEDGER_ID
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          -- AND XAH.JE_CATEGORY_NAME = CAT.CODE
          AND MIC.CATEGORY_SET_ID = 1
          --    AND CAT.APPLICATION_ID = 101
          AND XAL.APPLICATION_ID = 555
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GXEH.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND GXEH.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND GXEH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
          AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND (   NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          --SubLedger to GL Joining Start
          AND XAH.LEDGER_ID = GJH.LEDGER_ID                  -- ADDED BY MAJID
          AND GIR.GL_SL_LINK_ID = XAL.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE = XAL.GL_SL_LINK_TABLE
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJL.JE_HEADER_ID = GIR.JE_HEADER_ID
          AND GJL.JE_LINE_NUM = GIR.JE_LINE_NUM
          AND FLEX.FLEX_VALUE_SET_ID = 1017040
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
--     AND XAH.JE_CATEGORY_NAME NOT IN ('OPM Inv Receipts', 'Receiving')
--AND GXEH.ENTITY_CODE <> 'PURCHASING'
;

CREATE OR REPLACE SYNONYM APPSRO.XX_GL_DETAILS_STATEMENT_V FOR APPS.XX_GL_DETAILS_STATEMENT_V;


GRANT SELECT ON APPS.XX_GL_DETAILS_STATEMENT_V TO APPSRO;