--CUSTOMER ORDER MST
SELECT ''ORDER_ID, 
       co.ORDER_NO, 
       ''ORDER_TYPE,--FUNCTION
       co.DATE_ENTERED AS ORDER_DATE,
       co.CUSTOMER_NO AS CUST_NO,
       ''DELIVERY_DATE
FROM CUSTOMER_ORDER_TAB co;

--CUST_ORDER_DTL
SELECT ''ORDER_DTL_ID,
       '' ORDER_MST_ID, 
       cl.CUSTOMER_NO as CUST_NO, 
       cl.ORDER_NO, 
       cl.PART_NO AS ITEM_CODE, 
       cl.SALES_UNIT_MEAS AS MSR_UNIT_CODE, 
       cl.CONTRACT AS LOCATION_CODE,
       co.CURRENCY_CODE AS CUR_CODE,
       ''CONV_RATE, --CONV_FACTOR(?)
       BUY_QTY_DUE AS QNTY,
       BASE_SALE_UNIT_PRICE AS RATE, 
       BUY_QTY_DUE AS ORDER_AMOUNT,
       ''PRIORITY,
       ''PRIORITY_DATE

FROM CUSTOMER_ORDER_LINE_TAB cl
INNER JOIN CUSTOMER_ORDER_TAB co
ON cl.order_no=co.order_no;

