SELECT 
    /*COUNT(*)*/
    H.YEAR,
    H.PERIOD,
    H.SHOP_CODE,
    H.ORIGINAL_ACCT_NO,
    H.ACCT_NO,
    H.PRODUCT_CODE,
    H.SALESMAN,
    TO_CHAR(H.ACTUAL_SALES_DATE, 'YYYY/MM/DD') ACTUAL_SALES_DATE,
    TO_CHAR(H.SALES_DATE, 'YYYY/MM/DD') SALES_DATE,
    H.CUSTOMER,
    IFSAPP.CUSTOMER_INFO_API.Get_Name(H.CUSTOMER) CUSTOMER_NAME,
    H.TEL_NO,
    H.NORMAL_CASH_PRICE CASH_PRICE,
    H.HIRE_CASH_PRICE,
    H.HIRE_PRICE,
    H.AMOUNT_FINANCED,
    H.MONTHLY_PAY,
    H.FIRST_PAY,
    H.DOWN_PAYMENT,
    H.LOC,
    H.ARR_MON,
    H.ARR_AMT,
    H.DEL_MON,
    ifsapp.get_sbl_del_amt(H.YEAR, H.PERIOD, H.ACCT_NO) DEL_AMT,
    H.ACT_OUT_BAL
FROM IFSAPP.HPNRET_FORM249_ARREARS_TAB H
WHERE H.ACT_OUT_BAL > 0 AND
  H.YEAR = '&year_i' AND
  H.PERIOD = '&month_i' AND
  H.SHOP_CODE LIKE '&shop_code' AND 
  H.DEL_MON >= '&del_mon'
ORDER BY H.SHOP_CODE, H.ACCT_NO, H.PRODUCT_CODE
